-- WN3 UNIT PRICE CREATED ON DEC.01.2021 BY JIMSHEN

SELECT a.RPAITX,(CASE WHEN a.RPBRCD IN ('VND') THEN a.RPAMVA/22685 ELSE a.RPAMVA END) AS RPAMVA,a.RPBLDT,a.RPZ0D7, T2.ITCLS
FROM AMFLIBW.ITMFPR a 
left join AMFLIBW.ITMRVA T2 on a.RPAITX=T2.ITNBR and a.RPZ0D7 = T2.STID 
WHERE a.RPZ0D7 = '35' AND a.RPAITX||a.RPZ0D7||a.RPBLDT IN 
(SELECT a.RPAITX||a.RPZ0D7||MAX(a.RPBLDT) RPBLDT
FROM AMFLIBW.ITMFPR a  WHERE a.RPZ0D7 = '35' GROUP BY a.RPAITX,a.RPZ0D7)
AND T2.ITCLS LIKE 'Z%'
