-- wANEK ONHAND BY LOC AND SUMMARY
SELECT t1.ITNBR, t1.HOUSE, t1.ITCLS, t1.MOHTQ, t1.WHSLC, t1.QTSYR, t1.ITDSC,t2.LLOCN, t2.LQNTY
FROM
(SELECT ITEMBL.ITNBR, ITEMBL.HOUSE, ITEMBL.ITCLS, ITEMBL.MOHTQ, ITEMBL.WHSLC, ITEMBL.QTSYR, ITMRVA.ITDSC
FROM AFILELIBW.ITBEXT ITBEXT, AMFLIBW.ITEMBL ITEMBL, AFILELIBW.ITMEXT ITMEXT, AMFLIBW.ITMRVA ITMRVA, AMFLIBW.WHSMST WHSMST
WHERE ITMRVA.ITNBR = ITEMBL.ITNBR AND ITMRVA.STID = WHSMST.STID AND ITBEXT.HOUSE = ITEMBL.HOUSE AND ITBEXT.ITNBR = ITEMBL.ITNBR 
AND ITBEXT.ITNBR = ITMRVA.ITNBR AND ITMEXT.ITNBR = ITBEXT.ITNBR AND ITMEXT.ITNBR = ITEMBL.ITNBR AND ITMEXT.ITNBR = ITMRVA.ITNBR 
AND ITEMBL.HOUSE = WHSMST.WHID 
AND (ITEMBL.HOUSE IN ('35','31','33') AND ITEMBL.MOHTQ<>0) AND  ITEMBL.WHSLC in ('FA00','BW01')) as t1
Left Join  AMFLIBW.SLQNTY t2  
on t1.ITNBR = t2.ITNBR and t1.HOUSE=t2.HOUSE and t1.WHSLC = t2.LLOCN




--wanek onhand by loc
SELECT t1.ITNBR, t1.HOUSE,t1.LLOCN, t1.LQNTY
FROM AMFLIBW.SLQNTY t1
WHERE t1.LQNTY<>0 AND t1.HOUSE IN ('35','31','33') AND  t1.LLOCN IN ('FA00','BW01')
ORDER BY t1.ITNBR


-- Onhand by loc + Summary
SELECT t1.ITNBR, t1.HOUSE,t1.LLOCN, t1.LQNTY, t2.ITCLS, t2.MOHTQ, t2.WHSLC, t2.QTSYR
FROM AMFLIBW.SLQNTY t1,AMFLIBW.ITEMBL t2
WHERE t2.ITNBR = t1.ITNBR AND t1.HOUSE=t2.HOUSE AND ((t1.LQNTY<>0) AND (t1.HOUSE IN ('35','31','33'))) AND  t1.LLOCN IN ('FA00','BW01')
ORDER BY t1.ITNBR




--wanek onhand summary
SELECT ITEMBL.ITNBR, ITEMBL.HOUSE, ITEMBL.ITCLS, ITEMBL.MOHTQ, ITEMBL.WHSLC, ITEMBL.QTSYR, ITMRVA.ITDSC
FROM AFILELIBW.ITBEXT ITBEXT, AMFLIBW.ITEMBL ITEMBL, AFILELIBW.ITMEXT ITMEXT, AMFLIBW.ITMRVA ITMRVA, AMFLIBW.WHSMST WHSMST
WHERE ITMRVA.ITNBR = ITEMBL.ITNBR AND ITMRVA.STID = WHSMST.STID AND ITBEXT.HOUSE = ITEMBL.HOUSE AND ITBEXT.ITNBR = ITEMBL.ITNBR 
AND ITBEXT.ITNBR = ITMRVA.ITNBR AND ITMEXT.ITNBR = ITBEXT.ITNBR AND ITMEXT.ITNBR = ITEMBL.ITNBR AND ITMEXT.ITNBR = ITMRVA.ITNBR 
AND ITEMBL.HOUSE = WHSMST.WHID 
AND (ITEMBL.HOUSE IN ('35','31','33') AND ITEMBL.MOHTQ<>0) AND  ITEMBL.WHSLC in ('FA00','BW01')