

-- GET OUTPUT SN
SELECT T1.AAFWHS,T1.AAITM#,CHAR(T1.AASER#) AS SN, to_date(T1.AAADAT||' '||right('000000'||ltrim(T1.AAATIM),6), 'yyyymmdd hh24:mi:ss') AS DATE
FROM DISTLIBW.ACTAUDT T1
WHERE T1.AAAPGM IN ('HJ111E') AND T1.AACOD2 IN ('IT') AND T1.AACOD3 IN ('HJ') 
AND T1.AAFWHS IN ('35') AND  T1.AAADAT BETWEEN CHAR(VARCHAR_FORMAT(current date -60 days,'YYYYMMDD'))  AND CHAR(VARCHAR_FORMAT(current date, 'YYYYMMDD'))

-- GET DESTINATION
SELECT CHAR(T1.AASER#) AS SN,
FROM DISTLIBW.ACTAUDT T1
WHERE T1.AAAPGM IN ('HJ111E') AND T1.AACOD2 IN ('IT') AND T1.AACOD3 IN ('HJ') 
AND T1.AAFWHS IN ('35') AND  T1.AAADAT BETWEEN CHAR(VARCHAR_FORMAT(current date -60 days,'YYYYMMDD'))  AND CHAR(VARCHAR_FORMAT(current date, 'YYYYMMDD'))
 