-- WANEK OPEN MO QUERY V01

SELECT MOMAST.STID, MOMAST.ORDNO, MOMAST.FITEM, MOMAST.ORQTY+MOMAST.QTDEV as QTY, MOMAST.QTYRC,
MOMAST.ODUDT,MOMAST.OSTAT, MOMAST.ITCL, MOMAST.JOBNO,MOMAST.CRDT, MOMAST.CRUS,FDESC
FROM G20ACF9V.AMFLIBW.MOMAST MOMAST
WHERE SUBSTR(MOMAST.ORDNO,1,2) In ('MX') AND MOMAST.ORQTY+MOMAST.QTDEV <>0
AND MOMAST.OSTAT in ('10','40','45') AND  MOMAST.FITEM NOT LIKE '%VN%'
--AND MOMAST.ODUDT between 1210801 AND 1210811 
ORDER BY MOMAST.ORDNO


-- WANEK OPEN MO QUERY V02
SELECT MOMAST.STID, MOMAST.ORDNO, MOMAST.FITEM, MOMAST.ORQTY+MOMAST.QTDEV as MO_QTY, MOMAST.QTYRC AS RECEIVED_QTY,MOMAST.ORQTY+MOMAST.QTDEV-MOMAST.QTYRC AS OPEN_QTY,
MOMAST.ODUDT,MOMAST.ITCL, MOMAST.JOBNO,MOMAST.CRDT, MOMAST.CRUS
FROM G20ACF9V.AMFLIBW.MOMAST MOMAST
WHERE SUBSTR(MOMAST.ORDNO,1,2) In ('MX','MU','MY') AND MOMAST.ORQTY+MOMAST.QTDEV <>0
AND MOMAST.OSTAT in ('10','40','45') AND  MOMAST.FITEM NOT LIKE '%VN%'
--AND MOMAST.ODUDT between 1210801 AND 1210811 
ORDER BY MOMAST.FITEM, MOMAST.ODUDT, MOMAST.ORDNO