-- WN3 UNIT PRICE CREATED ON DEC.01.2021 BY JIMSHEN

SELECT a.RPAITX,(CASE WHEN a.RPBRCD IN ('VND') THEN a.RPAMVA/22685 ELSE a.RPAMVA END) AS RPAMVA,a.RPBLDT,a.RPZ0D7, T2.ITCLS
FROM AMFLIBW.ITMFPR a 
left join AMFLIBW.ITMRVA T2 on a.RPAITX=T2.ITNBR and a.RPZ0D7 = T2.STID 
WHERE a.RPZ0D7 = '35' AND a.RPAITX||a.RPZ0D7||a.RPBLDT IN 
(SELECT a.RPAITX||a.RPZ0D7||MAX(a.RPBLDT) RPBLDT
FROM AMFLIBW.ITMFPR a  WHERE a.RPZ0D7 = '35' GROUP BY a.RPAITX,a.RPZ0D7)
AND T2.ITCLS LIKE 'Z%'





-- WNK Unit Price created by JimShen on Nov.05.2021 

Select a.RPZ0D7,a.RPAITX,a.RPBLDT,
	(CASE 	
		WHEN a.RPBRCD IN ('USD') THEN a.RPAMVA 
		WHEN a.RPBRCD IN ('VND') THEN a.RPAMVA/22685
		ELSE 0 END) AS "UP($USD)"
From AMFLIBW.ITMFPR a 
WHERE a.RPZ0D7 IN ('35')
AND EXISTS
	(SELECT 1 FROM 
		(Select b.RPZ0D7,b.RPAITX,MAX(b.RPBLDT) AS EDATE
		From AMFLIBW.ITMFPR b WHERE b.RPZ0D7 IN ('35')
		GROUP BY b.RPZ0D7,b.RPAITX) AS x
	WHERE a.RPZ0D7=x.RPZ0D7 and a.RPAITX=x.RPAITX and a.RPBLDT=x.EDATE)




