-- wanek2 container utlization DETAILS UPDATED ON NOV.22.2021 
SELECT WCIORIGIN,CONTAINER#,CUBES,ITCLS,PRODUCT,WCIDESTINATION,WCIORDER,ITEMNUMBER,QTY,WCILASTMAINTENANCETIMESTAMP,CONTAINERNUMBER,DISTINCTCONTAINER,
WCILASTMAINTENANCEUSER,ITMCQTY,UNITCUBE,UNITWEIGHT,CARTONS,CONTAINERTYPE,Date,WCHCONTAINERSIZE,
(case 
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '40H' then CUBES/2650
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '40' then CUBES/2383
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '45' then CUBES/3058
	when substr(WCHCONTAINERSIZE,1,1) = '2' then CUBES/1191
	ELSE CUBES/2650 END) AS Utilization

FROM
(SELECT s1.ContainerNumber,s1.WCIORIGIN,s1.WCIDESTINATION,s1.WCIORDER,s1.ItemNumber,s1.Qty,s1.WCILASTMAINTENANCETIMESTAMP,s1.WCILASTMAINTENANCEUSER,s1.ITMCQTY,
s1.itcls,s1.UnitCube,s1.UnitWeight,s1.Cubes,s1.Cartons,s1.Product,s2.ContainerType,to_char(s1.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') as Date, 
s2.Container#,s1.Cubes/2650 as Utilization
FROM 
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) as Container#,
(CASE 
        WHEN a.WCIITEMNUMBER LIKE 'B%'  then 'CG'
        WHEN c.ITCLS not LIKE 'Z%'  then 'RP'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%K' then 'Un-Kits'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%Z' then 'ZipperCover'
        ELSE 'UPH' END) as Product
FROM WWUSAF.WVCNTID as a, AFILELIBW.ITMEXT as b, AMFLIBW.ITMRVA as c 
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('33')
and a.WCICONTAINERNUMBER not like 'SUNR2%'   
and  a.WCILASTMAINTENANCETIMESTAMP  between char(current date - 21 days) and char(current DATE)  
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)

union all

(SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||SUBSTR(char(a.WCIARCHIVETIMESTAMP),1,13) as Container#,
(CASE 
        WHEN a.WCIITEMNUMBER LIKE 'B%'  then 'CG'
        WHEN c.ITCLS not LIKE 'Z%'  then 'RP'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%K' then 'Un-Kits'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%Z' then 'ZipperCover'
        ELSE 'UPH' END) as Product
FROM ASHLEYARCW.WVCNTIDA as a, AFILELIBW.ITMEXT as b, AMFLIBW.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('33') 
and a.WCICONTAINERNUMBER not like 'SUNR2%' 
and a.WCILASTMAINTENANCETIMESTAMP  
between char(current date - 21 days) and char(current DATE)  AND substr(a.WCICONTAINERNUMBER,1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)) as s1,


(SELECT Container#,(case when count(Distinct PRODUCT)=1 then 'None-Mixed'  else 'Mixed' end) as ContainerType
FROM 
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) as Container#,
(CASE 
        WHEN a.WCIITEMNUMBER LIKE 'B%'  then 'CG'
        WHEN c.ITCLS not LIKE 'Z%'  then 'RP'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%K' then 'Un-Kits'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%Z' then 'ZipperCover'
        ELSE 'UPH' END) as Product
FROM WWUSAF.WVCNTID as a, AFILELIBW.ITMEXT as b, AMFLIBW.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('33')
and a.WCICONTAINERNUMBER not like 'SUNR2%'  
and  a.WCILASTMAINTENANCETIMESTAMP BETWEEN char(current date - 21 days) and char(current DATE) 
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)

union all

(SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||SUBSTR(char(a.WCIARCHIVETIMESTAMP),1,13) as Container#,
(CASE 
        WHEN a.WCIITEMNUMBER LIKE 'B%'  then 'CG'
        WHEN c.ITCLS not LIKE 'Z%'  then 'RP'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%K' then 'Un-Kits'
        WHEN c.ITCLS LIKE 'Z%' and c.ITCLS LIKE '%Z' then 'ZipperCover'
        ELSE 'UPH' END) as Product
FROM ASHLEYARCW.WVCNTIDA as a, AFILELIBW.ITMEXT as b, AMFLIBW.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('33') 
and a.WCICONTAINERNUMBER not like 'SUNR2%'
and a.WCILASTMAINTENANCETIMESTAMP 
between char(current date - 21 days) and char(current DATE) AND substr(a.WCICONTAINERNUMBER,1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION))
group by WCIORIGIN, Container#
order by Container#) as s2

WHERE s1.Container# = s2.Container#
order by s1.WCIORIGIN,s1.ContainerNumber,s1.WCILASTMAINTENANCETIMESTAMP
) AS Y1

right join

(Select DISTINCT(x1.Container#) as DistinctContainer, WCHCONTAINERSIZE

FROM
(SELECT 
a.WCHCONTAINERNUMBER,a.WCHORIGIN,a.WCHDESTINATION,a.WCHCONTAINERSTATUS,a.WCHTOTALCARTONS,a.WCHTOTALCUBES,a.WCHPOSTEDTIMESTAMP,a.WCHTOTALWEIGHT,
 a.WCHCONTAINERSIZE,
 trim(a.WCHORIGIN)||'-'|| trim(a.WCHCONTAINERNUMBER)||'-'||trim(a.WCHDESTINATION) as Container#
FROM  WWUSAF.WVCNTHD a
WHERE a.WCHCONTAINERSTATUS in ('P','T') AND a.WCHORIGIN IN ('33') and (a.WCHACTUALARRIVALMAINTPROGRAM='SVCHECKIN' 
OR (a.WCHACTUALARRIVALMAINTPROGRAM not in ('SVCHECKIN') and WCHBUILDING in ('33'))) and a.WCHCONTAINERNUMBER not like 'SUNR2%'
AND a.WCHCONTAINERNUMBER not like 'AIR%'  AND a.WCHDESTINATION NOT IN ('100','101','102','12','131','01','3','990') AND a.WCHBUILDING NOT IN ('B2','B4','B5')
AND a.WCHPOSTEDTIMESTAMP BETWEEN char(current date - 14 days) and char(current DATE) 
and substr(trim(a.WCHCONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')

union all

SELECT  a.WCHCONTAINERNUMBER,a.WCHORIGIN,a.WCHDESTINATION,a.WCHCONTAINERSTATUS,a.WCHTOTALCARTONS,a.WCHTOTALCUBES,a.WCHPOSTEDTIMESTAMP,a.WCHTOTALWEIGHT,a.WCHCONTAINERSIZE,
trim(a.WCHORIGIN)||'-'|| trim(a.WCHCONTAINERNUMBER)||'-'||trim(a.WCHDESTINATION)||'-'||SUBSTR(char(a.WCHARCHIVETIMESTAMP),1,13) as Container#
FROM  ASHLEYARCW.WVCNTHDA a
WHERE a.WCHCONTAINERSTATUS in ('P','T') and (a.WCHACTUALARRIVALMAINTPROGRAM='SVCHECKIN'
OR (a.WCHACTUALARRIVALMAINTPROGRAM not in ('SVCHECKIN') and WCHBUILDING in ('33'))) and a.WCHCONTAINERNUMBER not like 'SUNR2%'
AND a.WCHCONTAINERNUMBER not like 'AIR%'  AND a.WCHDESTINATION NOT IN ('100','101','102','12','131','01','3','990') AND a.WCHBUILDING NOT IN ('B2','B4','B5')
AND a.WCHPOSTEDTIMESTAMP BETWEEN char(current date - 14 days) and char(current DATE)  and a.WCHORIGIN in ('33') and 
substr(trim(a.WCHCONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')) as x1) as Y2


ON Y1.Container# = Y2.DistinctContainer

