SELECT T1.LIWHSE, T1.LIAREA, T1.LIASLE, T1.LISEC, T1.LITIER, T1.LIITEM, 
T1.LIIQTY, T1.LIIDSC, T1.LIMDAT, T1.LIMTME, T1.LIMUSR, T1.LIMPGM
FROM DISTLIBL.LOCINV T1
WHERE (T1.LIWHSE='51') AND (T1.LIIQTY <>0) AND T1.LIITEM LIKE '%UN' AND T1.LIITEM NOT LIKE 'M%' 
ORDER BY T1.LIITEM
