SELECT t1.ITNBR,t2.ITNBR,t2.HOUSE, t2.MOHTQ, t2.WHSLC,t2.ITCLS, t2.QTSYR, t4.B2Z95S, t4.ITDSC, t1.TIHIUNLD, t1.PICKPUT, t1.ITMCLSID, t1.UNITSWIDE, t1.UNITLAYERS, t1.UNITSDEEP, t1.SCOOPQTY, t1.SKIDSIZE, t3.QTYCR, t3.NBSEAT, t3.CRTWIN, t3.CRTLIN, t3.CRTHIN, t3.PRDWIN, t3.PRDHIN, t3.PRDLIN, t3.ITMWEGHT,t5.OpenCO
FROM AFILELIBL.ITBEXT t1,AFILELIBL.ITMEXT t3, AMFLIBL.ITMRVA t4,AMFLIBL.ITEMBL t2


LEFT JOIN
(
SELECT CDAITX as ITEM,sum(CDAGNV) as OpenCO
FROM AMFLIBL.MBCDRESM MBCDRESM
WHERE CDAGNV >0 and CDGLCD like 'Z%' and CDGLCD not like '%K' and CDA3CD IN ('51')
GROUP BY CDAITX
) as t5

ON t2.ITNBR=t5.ITEM

WHERE t1.ITNBR = t4.ITNBR AND t2.HOUSE = t1.HOUSE AND t2.ITNBR = t1.ITNBR AND t2.ITNBR = t4.ITNBR AND t2.ITCLS = t4.ITCLS AND t3.ITNBR = t1.ITNBR AND t3.ITNBR = t2.ITNBR AND t3.ITNBR = t4.ITNBR AND t4.STID = t1.HOUSE AND t1.HOUSE IN ('51') AND t2.ITCLS like 'Z%' and t2.itcls not like '%K'