
SELECT y1.ITEM#,y2.ITDSC,y2.ITCLS,y2.B2Z95S*(y1.WH#51+y1.WH#52) AS "OnHandCubes",
(CASE 
        WHEN y2.ITCLS IN ('SLDK') THEN 'RP'
        WHEN y2.ITCLS LIKE 'T%' THEN 'RP'
		WHEN y2.ITCLS LIKE 'R%' THEN 'RP'
		WHEN y2.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN y2.ITCLS LIKE 'Z%' AND y2.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN y2.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU') THEN 'UPH'
        WHEN y2.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN y2.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN y2.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN y2.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN y2.ITCLS IN ('PANL') THEN 'Panel'
		WHEN y2.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN y2.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN y2.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial'
        ELSE 'Check' END) AS Product,
y1.WH#51,y1.WH#52,y1.WH#00000001,y1.WH#001,y1.WH#1,y1.WH#101,y1.WH#102,y1.WH#103,y1.WH#105,y1.WH#12,y1.WH#15,y1.WH#16,y1.WH#17,y1.WH#18,y1.WH#19,y1.WH#20,y1.WH#21,y1.WH#213,y1.WH#215,y1.WH#232,y1.WH#242,y1.WH#28,y1.WH#3,y1.WH#31,y1.WH#335,y1.WH#42,y1.WH#49,y1.WH#5,y1.WH#50,y1.WH#60,y1.WH#70,y1.C,y1.C99,y1.CNW,y1.ECR 
 
-- ADDING ITCLS AND PRODUCTS
FROM 
(SELECT 
(CASE WHEN x2.WCIITEMNUMBER<>'' THEN x2.WCIITEMNUMBER ELSE x1.ITNBR END) as ITEM#,
x1.WH#51,x1.WH#52,x2.WH#00000001,x2.WH#001,x2.WH#1,x2.WH#101,x2.WH#102,x2.WH#103,x2.WH#105,x2.WH#12,x2.WH#15,x2.WH#16,x2.WH#17,x2.WH#18,x2.WH#19,x2.WH#20,x2.WH#21,x2.WH#213,x2.WH#215,x2.WH#232,x2.WH#242,x2.WH#28,x2.WH#3,x2.WH#31,x2.WH#335,x2.WH#42,x2.WH#49,x2.WH#5,x2.WH#50,x2.WH#60,x2.WH#70,x2.C,x2.C99,x2.CNW,x2.ECR  

FROM 
(
-- MIL OnHand
SELECT t1.ITNBR, 
SUM(CASE WHEN t1.HOUSE IN ('51') THEN t1.LQNTY ELSE 0 END) AS "WH#51",
SUM(CASE WHEN t1.HOUSE IN ('52') THEN t1.LQNTY ELSE 0 END) AS "WH#52"
FROM AMFLIBL.SLQNTY t1  WHERE t1.LLOCN IN ('FA00')
GROUP BY t1.ITNBR
) x1

FULL JOIN
( 
-- MIL loaded scanned into container but still not SA containers' summarized
SELECT a1.WCIITEMNUMBER,
SUM(CASE WHEN a1.WCIDESTINATION IN ('00000001') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#00000001",
SUM(CASE WHEN a1.WCIDESTINATION IN ('001') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#001",
SUM(CASE WHEN a1.WCIDESTINATION IN ('1') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#1",
SUM(CASE WHEN a1.WCIDESTINATION IN ('101') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#101",
SUM(CASE WHEN a1.WCIDESTINATION IN ('102') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#102",
SUM(CASE WHEN a1.WCIDESTINATION IN ('103') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#103",
SUM(CASE WHEN a1.WCIDESTINATION IN ('105') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#105",
SUM(CASE WHEN a1.WCIDESTINATION IN ('12') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#12",
SUM(CASE WHEN a1.WCIDESTINATION IN ('15') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#15",
SUM(CASE WHEN a1.WCIDESTINATION IN ('16') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#16",
SUM(CASE WHEN a1.WCIDESTINATION IN ('17') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#17",
SUM(CASE WHEN a1.WCIDESTINATION IN ('18') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#18",
SUM(CASE WHEN a1.WCIDESTINATION IN ('19') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#19",
SUM(CASE WHEN a1.WCIDESTINATION IN ('20') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#20",
SUM(CASE WHEN a1.WCIDESTINATION IN ('21') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#21",
SUM(CASE WHEN a1.WCIDESTINATION IN ('213') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#213",
SUM(CASE WHEN a1.WCIDESTINATION IN ('215') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#215",
SUM(CASE WHEN a1.WCIDESTINATION IN ('232') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#232",
SUM(CASE WHEN a1.WCIDESTINATION IN ('242') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#242",
SUM(CASE WHEN a1.WCIDESTINATION IN ('28') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#28",
SUM(CASE WHEN a1.WCIDESTINATION IN ('3') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#3",
SUM(CASE WHEN a1.WCIDESTINATION IN ('31') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#31",
SUM(CASE WHEN a1.WCIDESTINATION IN ('335') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#335",
SUM(CASE WHEN a1.WCIDESTINATION IN ('42') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#42",
SUM(CASE WHEN a1.WCIDESTINATION IN ('49') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#49",
SUM(CASE WHEN a1.WCIDESTINATION IN ('5') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#5",
SUM(CASE WHEN a1.WCIDESTINATION IN ('50') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#50",
SUM(CASE WHEN a1.WCIDESTINATION IN ('60') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#60",
SUM(CASE WHEN a1.WCIDESTINATION IN ('70') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "WH#70",
SUM(CASE WHEN a1.WCIDESTINATION IN ('C') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "C",
SUM(CASE WHEN a1.WCIDESTINATION IN ('C99') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "C99",
SUM(CASE WHEN a1.WCIDESTINATION IN ('CNW') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "CNW",
SUM(CASE WHEN a1.WCIDESTINATION IN ('ECR') THEN a1.WCIQUANTITYLOADED ELSE 0 END) AS "ECR"
FROM 
(
SELECT t1.WCICONTAINERNUMBER,t1.WCIORIGIN,t1.WCIDESTINATION,t1.WCIORDER,t1.WCIITEMNUMBER,t1.WCIQUANTITYREQUIRED,t1.WCIQUANTITYLOADED,t1.WCILASTMAINTENANCETIMESTAMP,
t1.WCILASTMAINTENANCEUSER,t1.WCILASTMAINTENANCEPROGRAM

FROM LLUSAF.WVCNTID t1, LLUSAF.WVCNTHD t2 
WHERE t1.WCICONTAINERNUMBER=t2.WCHCONTAINERNUMBER AND t1.WCIORIGIN=t2.WCHORIGIN
AND t2.WCHCONTAINERSTATUS NOT IN ('P','T')
) a1
GROUP BY a1.WCIITEMNUMBER
) x2
ON x1.ITNBR = x2.WCIITEMNUMBER
) y1, AMFLIBL.ITMRVA y2  
WHERE y1.ITEM#=y2.ITNBR
ORDER BY y1.ITEM#




