

SELECT t1.WCICONTAINERNUMBER,t1.WCIORIGIN,t1.WCIDESTINATION,t1.WCIORDER,t1.WCIITEMNUMBER,t1.WCIQUANTITYREQUIRED,t1.WCIQUANTITYLOADED,t1.WCILASTMAINTENANCETIMESTAMP,
t1.WCILASTMAINTENANCEUSER,t1.WCILASTMAINTENANCEPROGRAM, t3.ITCLS,
(CASE 
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
		WHEN t3.ITCLS LIKE 'R%' THEN 'RP'
		WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial'
        ELSE 'Check' END) AS Product

FROM LLUSAF.WVCNTID t1, LLUSAF.WVCNTHD t2, AMFLIBL.ITMRVA t3  
WHERE t1.WCICONTAINERNUMBER=t2.WCHCONTAINERNUMBER AND t1.WCIORIGIN=t2.WCHORIGIN AND t1.WCIITEMNUMBER=t3.ITNBR 
AND t2.WCHCONTAINERSTATUS NOT IN ('P','T')
ORDER BY t1.WCICONTAINERNUMBER, t1.WCIITEMNUMBER