
-- MIL Container shipped by time range --- 20210818
SELECT 
WCIORIGIN,CONTAINER#,CUBES,ITCLS,PRODUCT,WCIDESTINATION,WCIORDER,ITEMNUMBER,QTY,WCILASTMAINTENANCETIMESTAMP,CONTAINERNUMBER,DISTINCTCONTAINER,
WCILASTMAINTENANCEUSER,ITMCQTY,UNITCUBE,UNITWEIGHT,CARTONS,CONTAINERTYPE,DATE,WCHCONTAINERSIZE,QTY*f2.RPAMVA as "ShippedAMT($USD)"
FROM 
(-- MIL Container Utilization Details report updated on Nov.23 by Jimshen
SELECT WCIORIGIN,CONTAINER#,CUBES,ITCLS,PRODUCT,WCIDESTINATION,WCIORDER,ITEMNUMBER,QTY,WCILASTMAINTENANCETIMESTAMP,CONTAINERNUMBER,DISTINCTCONTAINER,
WCILASTMAINTENANCEUSER,ITMCQTY,UNITCUBE,UNITWEIGHT,CARTONS,CONTAINERTYPE,Date,WCHCONTAINERSIZE,
(case 
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '40H' then CUBES/2650
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '40' then CUBES/2383
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '45' then CUBES/3058
	when substr(WCHCONTAINERSIZE,1,1) = '2' then CUBES/1191
	ELSE CUBES/2650 END) AS Utilization

FROM
(SELECT s1.ContainerNumber,s1.WCIORIGIN,s1.WCIDESTINATION,s1.WCIORDER,s1.ItemNumber,s1.Qty,s1.WCILASTMAINTENANCETIMESTAMP,s1.WCILASTMAINTENANCEUSER,s1.ITMCQTY,
s1.itcls,s1.UnitCube,s1.UnitWeight,s1.Cubes,s1.Cartons,s1.Product,s2.ContainerType,to_char(s1.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') as Date, 
s2.Container#
FROM 
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) as Container#,
(CASE 
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
		WHEN c.ITCLS LIKE 'R%' THEN 'RP'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN c.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU') THEN 'UPH'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZECD') THEN 'CG'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN c.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN c.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial' 
        ELSE 'Check' END) AS Product
FROM LLUSAF.WVCNTID as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c 
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51')  
and  a.WCILASTMAINTENANCETIMESTAMP  between ? and ?  
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)

union all

(SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||SUBSTR(char(a.WCIARCHIVETIMESTAMP),1,13) as Container#,
(CASE 
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
		WHEN c.ITCLS LIKE 'R%' THEN 'RP'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN c.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU') THEN 'UPH'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZECD') THEN 'CG'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN c.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN c.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial' 
        ELSE 'Check' END) AS Product
FROM ASHLEYARCL.WVCNTIDA as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51') and a.WCILASTMAINTENANCETIMESTAMP  
between ? and ?  AND substr(a.WCICONTAINERNUMBER,1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)) as s1,

-- TABLE.S2 to judge container type (combined or non-conbined)
(SELECT Container#,(case when count(Distinct PRODUCT)=1 then 'None-Mixed'  else 'Mixed' end) as ContainerType
FROM 
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) as Container#,
(CASE 
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
		WHEN c.ITCLS LIKE 'R%' THEN 'RP'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN c.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU') THEN 'UPH'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZECD') THEN 'CG'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN c.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN c.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial' 
        ELSE 'Check' END) AS Product
FROM LLUSAF.WVCNTID as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51')  
and  a.WCILASTMAINTENANCETIMESTAMP  between ? and ? 
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)

union all

(SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, 
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,
CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||SUBSTR(char(a.WCIARCHIVETIMESTAMP),1,13) as Container#,
(CASE 
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
		WHEN c.ITCLS LIKE 'R%' THEN 'RP'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN c.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU') THEN 'UPH'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZECD') THEN 'CG'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN c.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN c.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial' 
        ELSE 'Check' END) AS Product
FROM ASHLEYARCL.WVCNTIDA as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51') and a.WCILASTMAINTENANCETIMESTAMP 
between ? and ?  AND substr(a.WCICONTAINERNUMBER,1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION))
group by WCIORIGIN, Container#
order by Container#) as s2

WHERE s1.Container# = s2.Container#
order by s1.WCIORIGIN,s1.ContainerNumber,s1.WCILASTMAINTENANCETIMESTAMP
) AS Y1
-- TABLE Y1 to get current and archived container loaded details

right join

(Select DISTINCT(x1.Container#) as DistinctContainer,WCHCONTAINERSIZE

FROM
(SELECT 
a.WCHCONTAINERNUMBER,a.WCHORIGIN,a.WCHDESTINATION,a.WCHCONTAINERSTATUS,a.WCHTOTALCARTONS,a.WCHTOTALCUBES,a.WCHPOSTEDTIMESTAMP,a.WCHTOTALWEIGHT,
a.WCHCONTAINERSIZE,
trim(a.WCHORIGIN)||'-'|| trim(a.WCHCONTAINERNUMBER)||'-'||trim(a.WCHDESTINATION) as Container#
FROM  LLUSAF.WVCNTHD a
WHERE a.WCHCONTAINERSTATUS in ('P','T') AND a.WCHORIGIN IN ('51')  AND a.WCHPOSTEDTIMESTAMP between ? and ?  
and substr(trim(a.WCHCONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')

union all

SELECT  a.WCHCONTAINERNUMBER,a.WCHORIGIN,a.WCHDESTINATION,a.WCHCONTAINERSTATUS,a.WCHTOTALCARTONS,a.WCHTOTALCUBES,a.WCHPOSTEDTIMESTAMP,a.WCHTOTALWEIGHT,a.WCHCONTAINERSIZE,
trim(a.WCHORIGIN)||'-'|| trim(a.WCHCONTAINERNUMBER)||'-'||trim(a.WCHDESTINATION)||'-'||SUBSTR(char(a.WCHARCHIVETIMESTAMP),1,13) as Container#
FROM  ASHLEYARCL.WVCNTHDA a
WHERE a.WCHCONTAINERSTATUS in ('P','T') AND a.WCHPOSTEDTIMESTAMP between ? and ?   and a.WCHORIGIN in ('51') and 
substr(trim(a.WCHCONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')) as x1) as Y2


ON Y1.Container# = Y2.DistinctContainer
) AS f1


left join 

(
-- MIL UNIT PRICE CREATED ON Feb.15.2022 BY JIMSHEN
SELECT b1.RPAITX, MAX(b1.RPAMVA) as RPAMVA
FROM 
(SELECT x.RPAITX, x.ITCLS, x.RPAMVA, x.RPBLDT, x.RPZ0D7
FROM
(
((SELECT a.RPAITX,(CASE WHEN a.RPBRCD IN ('VND') THEN a.RPAMVA/23090 ELSE a.RPAMVA END) AS RPAMVA,a.RPBLDT,a.RPZ0D7, T2.ITCLS
FROM AMFLIBL.ITMFPR a 
LEFT JOIN AMFLIBL.ITMRVA T2 ON a.RPAITX=T2.ITNBR AND a.RPZ0D7 = T2.STID 
WHERE a.RPZ0D7 = '51' AND a.RPAITX||a.RPZ0D7||a.RPBLDT IN (SELECT a.RPAITX||a.RPZ0D7||MAX(a.RPBLDT) RPBLDT FROM AMFLIBL.ITMFPR a  WHERE a.RPZ0D7 = '51' GROUP BY a.RPAITX,a.RPZ0D7)) 
UNION ALL
(SELECT t1.ITNO1G, t1.UCCT1G/23090 AS RPAMVA, t1.CCDT1G, t1.STID1G, t1.STID1G FROM AMFLIBL.ITMPRB t1))
UNION ALL
(SELECT t1.ITNBR, t1.LCOST/23090 AS RPAMVA, t1.LDQOH, t1.HOUSE, t1.ITCLS FROM AMFLIBL.ITEMBL t1))AS x
ORDER BY x.RPAITX, x.RPAMVA ASC) b1
GROUP BY b1.RPAITX
) f2
on f1.ITEMNUMBER = f2.RPAITX 