--RM RECEIVED TIME, created by Jimshen On Oct.10.2022
SELECT t1.AACOD1,t1.AACOD2,t1.AAORD#,TRIM(t1.AAITM#) AAITM#,CHAR(t1.AASER#) as SN,to_date(t1.AAADAT||' '||right('000000'||ltrim(t1.AAATIM),6), 'yyyymmdd hh24:mi:ss') as "HJ_Received_Time", t1.AAAPGM, t3.ITCLS,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
		WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product
FROM DISTLIBL.ACTAUDT t1, (SELECT t2.ITNBR,T2.ITCLS FROM AMFLIBL.ITMRVA T2 WHERE T2.STID IN ('51')) t3
WHERE  t1.AAADAT Between CHAR(VARCHAR_FORMAT(current date -60 days,'YYYYMMDD'))  AND CHAR(VARCHAR_FORMAT(current date, 'YYYYMMDD'))  AND t1.AACOD1 IN ('RM')
AND t1.AAITM# = t3.ITNBR        
AND NOT EXISTS
--MOVE,CN,UL
(SELECT 1
FROM 
(
SELECT CHAR(t1.AASER#) as SN
FROM DISTLIBL.ACTAUDT t1
WHERE  t1.AAADAT Between CHAR(VARCHAR_FORMAT(current date -70 days,'YYYYMMDD'))  AND CHAR(VARCHAR_FORMAT(current date, 'YYYYMMDD'))  AND t1.AACOD1 IN ('MV','CN','UL') 
GROUP BY CHAR(t1.AASER#)
) b1 
WHERE CHAR(t1.AASER#) = b1.SN)

AND EXISTS
-- MIL OPEN MO BY P&IC, Created by Jimshen on Sep.28.2021
(SELECT 1
FROM
(SELECT t1.STID, t1.ORDNO, t1.FITEM, t1.ORQTY+t1.QTDEV as MO_QTY, t1.QTYRC AS RECEIVED_QTY,t1.ORQTY+t1.QTDEV-t1.QTYRC AS OPEN_QTY,
t1.ODUDT,t1.ITCL, t1.JOBNO,t1.CRDT, t1.CRUS		
FROM AMFLIBL.MOMAST t1
WHERE t1.ORQTY+t1.QTDEV-t1.QTYRC <>0
AND t1.OSTAT in ('10','40','45') 
--AND t1.ODUDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 90 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
ORDER BY t1.FITEM, t1.ODUDT, t1.ORDNO) as d1
WHERE t1.AAORD#||TRIM(t1.AAITM#) = d1.ORDNO||d1.FITEM)

