-- MIL ON HAND WITH BOX_MRP AND BOX_DES CREATED BY JIMSHEN UPDATED ON Aug.24.2022
SELECT a1.ITNBR, a1.ITDSC,a1.B2Z95S*a1.LQNTY as Cubes, a1.ITCLS, a1.HOUSE, a1.LLOCN, a1.LQNTY, a1.ORDNO, a1.LBHNO, 
(CASE 
        WHEN a1.ITCLS LIKE 'TAF%' THEN 'RP'
		WHEN a1.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN a1.ITCLS LIKE 'Z%' AND a1.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN a1.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN a1.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN a1.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN a1.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN a1.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN a1.ITCLS IN ('PANL') THEN 'Panel'
		WHEN a1.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN a1.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN a1.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product,
b1.BXDCOMPONENTITEMNUMBER as BOX_MRP, b1.BXDCOMPONENTITEMDESCRIPTION as BOX_DES
FROM
(
-- MIL Inv Qty
SELECT t1.ITNBR, t2.ITDSC, t2.ITCLS, t1.HOUSE, t1.LLOCN, t1.FDATE, t1.LQNTY, t1.ORDNO, t1.LBHNO, t2.B2Z95S
FROM AMFLIBL.SLQNTY t1 left join AMFLIBL.ITMRVA t2 on t1.itnbr = t2.itnbr
WHERE t1.LLOCN IN ('FA00') AND TRIM(t1.ITNBR) LIKE '%UN'
) a1

LEFT JOIN 
-- GET BOX_MRP and BOX_DES FROM BOM
(SELECT T1.BXDSTID,T1.BXDPARENTITEMNUMBER,T1.BXDCOMPONENTITEMNUMBER, T1.BXDCOMPONENTITEMDESCRIPTION
FROM RGNFILL.PSTBOMD T1
Where  T1.BXDSTID IN ('51') AND TRIM(T1.BXDPARENTITEMNUMBER) LIKE '%UN' AND (T1.BXDCOMPONENTITEMDESCRIPTION LIKE 'RSC%'  OR  T1.BXDCOMPONENTITEMDESCRIPTION  LIKE  'UWALL%')) AS b1
ON a1.HOUSE = b1.BXDSTID AND TRIM(a1.ITNBR)= TRIM(b1.BXDPARENTITEMNUMBER)



/*
-- by product to accumulate the product as string, made by JimShen on Jul.18.2022
select a8.WCIORIGIN,a8.CONTAINER#,a8.CONTAINERTYPE,replace(replace(xml2clob(xmlagg(xmlelement(NAME A, a8.PRODUCT||','))),'<A>',''),'</A>','') as PRODUCT 
FROM
(
SELECT a9.WCIORIGIN,a9.CONTAINER#,a9.PRODUCT,a9.CONTAINERTYPE
FROM 
(...........)
) a8
GROUP BY a8.WCIORIGIN,a8.CONTAINER#,a8.CONTAINERTYPE
*?