-- MIL Container Scanned QUERY by JimShen on Jun.20.2022

(--Current files for scanned into containers by LLUSAF.WVCNTSD-SN and RGNFILL.PC228RPF
SELECT *
FROM 
(
(SELECT t1.WCSCONTAINERNUMBER, t1.WCSORIGIN, t1.WCSDESTINATION, t1.WCSORDER, t1.WCSITEMNUMBER,t3.ITCLS, DATE(t1.WCSADDEDTIMESTAMP) AS DATE, HOUR(t1.WCSADDEDTIMESTAMP) AS Hour,
t1.WCSADDEDUSER,t2.ITMCQTY, t3.B2Z95S,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product, 
COUNT(t1.WCSSERIALNUMBER) AS LOADED_QTY, COUNT(t1.WCSSERIALNUMBER)/t2.ITMCQTY AS BoxQty, COUNT(t1.WCSSERIALNUMBER)*t3.B2Z95S AS CUBES
		
FROM DISTLIBL.TBL_WVCONTAINER_DTL_SER  t1, AFILELIBL.ITMEXT t2, AMFLIBL.ITMRVA t3
WHERE  t1.WCSITEMNUMBER= t2.ITNBR AND t1.WCSCONTAINERNUMBER NOT LIKE  'KHOA%' AND t1.WCSITEMNUMBER = t3.itnbr AND t1.WCSORIGIN=t3.stid
GROUP BY t1.WCSCONTAINERNUMBER, t1.WCSORIGIN, t1.WCSDESTINATION, t1.WCSORDER, t1.WCSITEMNUMBER,t3.ITCLS, DATE(t1.WCSADDEDTIMESTAMP), HOUR(t1.WCSADDEDTIMESTAMP),
t1.WCSADDEDUSER,t2.ITMCQTY, t3.B2Z95S,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END)

ORDER BY t1.WCSCONTAINERNUMBER)

UNION ALL

(SELECT t1.RPLCONTAINERNUMBER, '51' AS WCSORIGIN, 'Null' AS WCSDESTINATION, 'Null' as WCSORDER, t1.RPLITEMNUMBER, t3.ITCLS, DATE(t1.RPLLOADDATE) AS DATE, HOUR(t1.RPLLOADDATE) AS HOUR, 
t1.RPLLOADUSERNAME,t2.ITMCQTY, t3.B2Z95S, 
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product, 
SUM(t1.RPLPRINTQUANTITY) AS LOADED_QTY, SUM(t1.RPLPRINTQUANTITY)/t2.ITMCQTY AS BoxQty, SUM(t1.RPLPRINTQUANTITY)*t3.B2Z95S AS CUBES

FROM RGNFILL.PC228RPF t1, AFILELIBL.ITMEXT t2, AMFLIBL.ITMRVA t3
WHERE  t1.RPLITEMNUMBER = t2.ITNBR AND t1.RPLITEMNUMBER = t3.itnbr
GROUP BY 
t1.RPLCONTAINERNUMBER,'51', 'Null', 'Null', t1.RPLITEMNUMBER, t3.ITCLS, DATE(t1.RPLLOADDATE), HOUR(t1.RPLLOADDATE), 
t1.RPLLOADUSERNAME,t2.ITMCQTY, t3.B2Z95S,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END))
) AS x
WHERE  x.WCSCONTAINERNUMBER = ?
ORDER BY x.WCSCONTAINERNUMBER, x.HOUR
)

UNION ALL

(--Archived files for scanned into containers by ASHLEYARCL.WVCNTSDA-SN and ASHLEYARCL.TBL_RPLABEL_ARCFILE_PC228RPFA
SELECT *
FROM 
(
(SELECT t1.WCSCONTAINERNUMBER, t1.WCSORIGIN, t1.WCSDESTINATION, t1.WCSORDER, t1.WCSITEMNUMBER,t3.ITCLS, DATE(t1.WCSADDEDTIMESTAMP) AS DATE, HOUR(t1.WCSADDEDTIMESTAMP) AS Hour,
t1.WCSADDEDUSER,t2.ITMCQTY, t3.B2Z95S,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product, 
COUNT(t1.WCSSERIALNUMBER) AS LOADED_QTY, COUNT(t1.WCSSERIALNUMBER)/t2.ITMCQTY AS BoxQty, COUNT(t1.WCSSERIALNUMBER)*t3.B2Z95S AS CUBES
		
FROM ASHLEYARCL.TBL_WVCONTAINER_DTL_SER_A t1, AFILELIBL.ITMEXT t2, AMFLIBL.ITMRVA t3
WHERE  t1.WCSITEMNUMBER= t2.ITNBR AND t1.WCSCONTAINERNUMBER NOT LIKE  'KHOA%' AND t1.WCSITEMNUMBER = t3.itnbr AND t1.WCSORIGIN=t3.stid
GROUP BY t1.WCSCONTAINERNUMBER, t1.WCSORIGIN, t1.WCSDESTINATION, t1.WCSORDER, t1.WCSITEMNUMBER,t3.ITCLS, DATE(t1.WCSADDEDTIMESTAMP), HOUR(t1.WCSADDEDTIMESTAMP),
t1.WCSADDEDUSER,t2.ITMCQTY, t3.B2Z95S,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END)
ORDER BY t1.WCSCONTAINERNUMBER)

UNION ALL

(SELECT t1.RPLCONTAINERNUMBER, '51' AS WCSORIGIN, 'Null' AS WCSDESTINATION, 'Null' as WCSORDER, t1.RPLITEMNUMBER, t3.ITCLS, DATE(t1.RPLLOADDATE) AS DATE, HOUR(t1.RPLLOADDATE) AS HOUR, 
t1.RPLLOADUSERNAME,t2.ITMCQTY, t3.B2Z95S, 
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product, 
SUM(t1.RPLPRINTQUANTITY) AS LOADED_QTY, SUM(t1.RPLPRINTQUANTITY)/t2.ITMCQTY AS BoxQty, SUM(t1.RPLPRINTQUANTITY)*t3.B2Z95S AS CUBES

FROM ASHLEYARCL.TBL_RPLABEL_ARCFILE_PC228RPFA t1, AFILELIBL.ITMEXT t2, AMFLIBL.ITMRVA t3
WHERE  t1.RPLITEMNUMBER = t2.ITNBR AND t1.RPLITEMNUMBER = t3.itnbr
GROUP BY 
t1.RPLCONTAINERNUMBER,'51', 'Null', 'Null', t1.RPLITEMNUMBER, t3.ITCLS, DATE(t1.RPLLOADDATE), HOUR(t1.RPLLOADDATE), 
t1.RPLLOADUSERNAME,t2.ITMCQTY, t3.B2Z95S,
(CASE 
        WHEN t3.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN t3.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END))
) AS x
WHERE  x.WCSCONTAINERNUMBER = ?
ORDER BY x.WCSCONTAINERNUMBER, x.HOUR
)