-- by product to accumulate the product as string, made by JimShen on Jul.18.2022
select a8.WCIORIGIN,a8.CONTAINERNUMBER,replace(replace(xml2clob(xmlagg(xmlelement(NAME A, a8.PRODUCT||'|'))),'<A>',''),'</A>','') as PRODUCT 
FROM
(
SELECT a9.WCIORIGIN,a9.CONTAINERNUMBER,a9.PRODUCT
FROM 



SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, trim(a.WCIITEMNUMBER) as ItemNumber,
a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER,c.itcls,
(CASE 
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
		WHEN c.ITCLS LIKE 'R%' THEN 'RP'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN c.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU') THEN 'UPH'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZECD') THEN 'CG'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN c.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN c.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial' 
        ELSE 'Check' END) AS Product
FROM DISTLIBL.TBL_WVCONTAINER_DTL_ITM as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c 
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51')  
and  a.WCILASTMAINTENANCETIMESTAMP  between char(current date - 30 days) and char(current DATE)  
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER


right join
-- TABLE Y2 to get current Container head files
(SELECT 
a.WCHCONTAINERNUMBER,a.WCHORIGIN,a.WCHDESTINATION,a.WCHCONTAINERSTATUS,a.WCHPOSTEDTIMESTAMP,a.WCHCONTAINERSIZE
FROM  DISTLIBL.TBL_WVCONTAINER_HDR a
WHERE a.WCHCONTAINERSTATUS in ('A','P','T','H','R') AND a.WCHORIGIN IN ('51')  AND a.WCHPOSTEDTIMESTAMP BETWEEN char(current date - 21 days) and char(current DATE) 
and substr(trim(a.WCHCONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
) Y2 
ON Y1.ContainerNumber = Y2.WCHCONTAINERNUMBER


) a9
GROUP BY a9.WCIORIGIN,a9.CONTAINERNUMBER,a9.PRODUCT
) a8
GROUP BY a8.WCIORIGIN,a8.CONTAINERNUMBER