-- MIL Container Utilization Details report updated on Nov.23 by Jimshen
SELECT Y1.WCIORIGIN,Y1.CONTAINERNUMBER,Y1.CUBES,Y1.ITCLS,Y1.PRODUCT,Y1.WCIDESTINATION,Y1.WCIORDER,Y1.ITEMNUMBER,Y1.QTY,
Y1.WCILASTMAINTENANCETIMESTAMP,Y1.WCILASTMAINTENANCEUSER,Y1.ITMCQTY,Y1.UNITCUBE,Y1.UNITWEIGHT,Y1.CARTONS,Y1.Date,Y2.WCHCONTAINERSIZE,
(case 
	when trim(substr(WCHCONTAINERSIZE,1,2)) = '53' then CUBES/3831
	when trim(substr(WCHCONTAINERSIZE,1,2)) = '50' then CUBES/3333
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '40H' then CUBES/2650
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '40' then CUBES/2383
	when trim(substr(WCHCONTAINERSIZE,1,3)) = '45' then CUBES/3058
	when substr(WCHCONTAINERSIZE,1,1) = '2' then CUBES/1191
	ELSE CUBES/2650 END) AS Utilization,
Y2.WCHCONTAINERSTATUS,Y2.WCHDOORNUMBER,Y2.WCHBUILDING,Y2.WCHSEALNUMBER,Y2.WCHCARRIER,Y2.WCHWEEKPO,timestamp(Y2.WCHACTUALARRIVALTIMESTAMP) as ACTUALARRIVALTIME,
Y2.WCHACTUALARRIVALMAINTUSER, timestamp(Y2.WCHFIRSTLOADINGTIMESTAMP) as FIRSTLOADINGTIME,  TIMESTAMP(Y2.WCHPOSTEDTIMESTAMP) as POSTEDTIME,
 TIMESTAMP(Y2.WCHLASTMAINTENANCETIMESTAMP) as LASTMAINTENANCETIME

FROM
(SELECT s1.ContainerNumber,s1.WCIORIGIN,s1.WCIDESTINATION,s1.WCIORDER,s1.ItemNumber,s1.Qty,s1.WCILASTMAINTENANCETIMESTAMP,s1.WCILASTMAINTENANCEUSER,s1.ITMCQTY, s1.itcls,s1.UnitCube,s1.UnitWeight,s1.Cubes,s1.Cartons,s1.Product,to_char(s1.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') as Date
FROM 
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, 
c.WEGHT as UnitWeight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes, CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
(CASE 
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
		WHEN c.ITCLS LIKE 'R%' THEN 'RP'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN c.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU') THEN 'UPH'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZECD') THEN 'CG'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN c.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
		WHEN c.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial' 
        ELSE 'Check' END) AS Product
FROM DISTLIBL.TBL_WVCONTAINER_DTL_ITM as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c 
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51')  
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)
) as s1
order by s1.WCIORIGIN,s1.ContainerNumber,s1.WCILASTMAINTENANCETIMESTAMP
) AS Y1

-- TABLE Y1 to get current and archived container loaded details

right join

(SELECT 
x1.WCHCONTAINERNUMBER,x1.WCHCONTAINERSIZE,x1.WCHDESTINATION,x1.WCHCONTAINERSTATUS,x1.WCHDOORNUMBER,x1.WCHBUILDING,x1.WCHSEALNUMBER,x1.WCHCARRIER,x1.WCHWEEKPO,x1.WCHACTUALARRIVALTIMESTAMP,x1.WCHACTUALARRIVALMAINTUSER,x1.WCHPOSTEDTIMESTAMP,x1.WCHFIRSTLOADINGTIMESTAMP,x1.WCHLASTMAINTENANCETIMESTAMP
FROM  DISTLIBL.TBL_WVCONTAINER_HDR x1
WHERE x1.WCHCONTAINERSTATUS in ('A','P','T','H','R') AND x1.WCHORIGIN IN ('51')  
and substr(trim(x1.WCHCONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1','AAII','ARRR')
) as Y2 
ON Y1.ContainerNumber = Y2.WCHCONTAINERNUMBER
ORDER BY Y1.CONTAINERNUMBER
