-- WH Trx Summary in qty and amount  DSN=MILPRODBI
SELECT X.TCODE,X.ITNBR, X.HOUSE, X.ITCLS,X.YEAR,X.TRQTY,
(CASE 
        WHEN X.ITCLS LIKE 'TAF%' THEN 'RP'
        WHEN X.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN X.ITCLS LIKE 'Z%' AND X.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN X.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'
        WHEN X.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'
        WHEN X.ITCLS IN ('ZKIS') THEN 'Bedding'		
        WHEN X.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN X.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'		
        WHEN X.ITCLS IN ('PANL') THEN 'Panel'
        WHEN X.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN X.ITCLS IN ('BBFR','WVHC') THEN 'Verona'		
        WHEN X.ITCLS NOT LIKE 'Z%' THEN 'Raw'
        ELSE 'Check' END) AS Product,
(CASE 
		WHEN X.TCODE IN ('RP','PQ','RM','RS','RC','IA','LA') THEN 'IN'
		WHEN X.TCODE IN ('SA','IP','IS','VR','IU','SC','SM','SP','SS') THEN 'OUT'
		ELSE 'CHECK' END ) as "TYPE"
	
FROM
(     
SELECT T1.TCODE,T1.ITNBR, T1.HOUSE, T2.ITCLS,
YEAR(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS YEAR,
SUM(T1.TRQTY) TRQTY
FROM AMFLIBL.IMHIST T1, AMFLIBL.ITMRVA T2, AMFLIBL.WHSMST T3
WHERE T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND T1.HOUSE='51' 
AND T1.UPDDT BETWEEN '1201201' AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
AND T1.TRQTY<>0 AND T1.TCODE IN ('RP','PQ','RM','RS','RC','IA','LA','SA','IP','IS','VR','IU','SC','SM','SP','SS') 
GROUP BY  T1.TCODE,T1.ITNBR, T1.HOUSE, T2.ITCLS, 
YEAR(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2)))
ORDER BY T1.ITNBR 
) AS X 


