-- MIL UNKITS STAGE REPORT ON DEC.16.2021
SELECT Y1.SN,Y1.TDTSTS,Y1.TDITEM,Y1.MO,Y1.TDWHSE,Y1.TDMDAT,Y1.TDMTME,Y1.TXT_TIME,Y1.ITCLS,(1/Y1.ITMCQTY) AS CARTONS, Y1.PRODUCT,Y1.SHIFT,Y1.LINE,Y2.CTN,Y2."CTN_STATUS" 
FROM
(
-- GET SERIAL NUMBERS FROM TAG AND STATUS IN 'R' AND 'S' IN RECENT 60 DAYS
SELECT X1.SN,X1.TDTSTS,X1.TDITEM,X1.MO,X1.TDWHSE,X1.TDMDAT,X1.TDMTME,X1.TXT_TIME,X1.ITCLS,X1.PRODUCT, X1.SHIFT,CHAR(TRIM(SUBSTR(X2.JOBNO,1,5))) AS LINE,X1.ITMCQTY 
FROM
(
SELECT CHAR(TRIM(T1.TDTAG#)) AS SN,T1.TDITEM,T1.TDAPO# AS MO,T1.TDWHSE,T1.TDMDAT,T1.TDMTME, T1.TDTSTS,RIGHT('000000'||LTRIM(T1.TDMTME),6) AS TXT_TIME,T3.ITCLS,T5.ITMCQTY, 
(CASE 
	WHEN T3.ITCLS IN ('WPLS') THEN 'PLASTICS' 
	WHEN T3.ITCLS IN ('WVBC','WVHC') THEN 'FOUNDATION' 
	WHEN T3.ITCLS IN ('SLDK') THEN 'RP' 
	WHEN T3.ITCLS LIKE 'T%' THEN 'RP' 
	WHEN T3.ITCLS IN ('ZKIS') THEN 'BEDDING' 
	WHEN T3.ITCLS IN ('ZKIZ') THEN 'ZIPPERCOVER' 
	WHEN T3.ITCLS LIKE 'Z%' AND T3.ITCLS LIKE '%K' THEN 'UNKITS' 
	WHEN T3.ITCLS IN ('PACS') THEN 'UNKITS' 
	WHEN T3.ITCLS IN ('BBFR') THEN 'FR SOCK' 
	WHEN T3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG' 
	WHEN T3.ITCLS LIKE 'Z%' THEN 'UPH' ELSE 'CHECK' END) AS PRODUCT, 
(CASE 
	WHEN T1.TDMTME BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END) AS SHIFT 
	
FROM DISTLIBL.TAGINVD T1,(SELECT DISTINCT T2.ITNBR,T2.ITCLS FROM AMFLIBL.ITEMBL T2 WHERE T2.HOUSE = '51' GROUP BY T2.ITNBR,T2.ITCLS) AS T3, 
(SELECT DISTINCT T4.ITNBR,T4.ITMCQTY FROM AFILELIBL.ITMEXT T4 GROUP BY T4.ITNBR,T4.ITMCQTY) AS T5 
WHERE T1.TDITEM = T3.ITNBR AND T1.TDITEM=T5.ITNBR AND T3.ITNBR=T5.ITNBR AND T1.TDTSTS IN ('R','S','') 
AND T1.TDMDAT BETWEEN  INT('1'||SUBSTR(TRIM(CHAR(CURRENT DATE - 60 DAYS)),3,2)||SUBSTR(TRIM(CHAR(CURRENT DATE- 60 DAYS)),6,2)||SUBSTR(TRIM(CHAR(CURRENT DATE- 60 DAYS)),9,2))  
AND INT('1'||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),3,2)||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),6,2)||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),9,2)) 
AND (T3.ITCLS LIKE 'Z%' AND T3.ITCLS NOT LIKE '%K' AND T3.ITCLS NOT IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZKIS','ZKIZ')) 
AND NOT EXISTS
	-- SN NOT EXISTS IN SHIPPED CONTAINERS AND ARCHIVED SHIPPED CONTAINERS IN RECENT 60 DAYS
	(SELECT 1 
	FROM ((SELECT CHAR(TRIM(A.WCSSERIALNUMBER)) AS SN FROM LLUSAF.WVCNTSD A, LLUSAF.WVCNTHD B WHERE A.WCSCONTAINERNUMBER = B.WCHCONTAINERNUMBER AND B.WCHCONTAINERSTATUS IN ('P','T') AND B.WCHPOSTEDTIMESTAMP BETWEEN CHAR(CURRENT DATE - 61 DAYS) AND CHAR(CURRENT DATE + 1 DAYS)) 
	UNION ALL 
	(SELECT CHAR(TRIM(A.WCSSERIALNUMBER)) AS SN 
	FROM ASHLEYARCL.WVCNTSDA A WHERE A.WCSADDEDTIMESTAMP BETWEEN CHAR(CURRENT DATE - 61 DAYS) AND CHAR(CURRENT DATE + 1 DAYS))) XX1 
	WHERE CHAR(TRIM(T1.TDTAG#)) = XX1.SN)
AND NOT EXISTS 
	-- CLOSED MO&ITEM NOT IN TAG FILE QUERY
	(SELECT 1 
    FROM (
			SELECT a.ORDNO,a.JOBNO,a.FITEM,a.OSTAT,a.QTYRC,a.ITCL,a.ORQTY-a.QTDEV AS OPENMOQTY  
			FROM AMFLIBL.MOMAST a 
			WHERE a.ITCL LIKE 'Z%' AND a.ITCL NOT LIKE '%K' AND a.FITEM NOT LIKE 'M%' AND a.OSTAT IN ('55')) AS J
	WHERE T1.TDAPO#||T1.TDITEM = J.ORDNO||J.FITEM)			
					
) AS X1 

LEFT JOIN 
-- GET PRODUCTION LINES FROM MOMAST AND MOHMST, THEN BY LINE TO JUDGE BUILDING IN BI REPORT.
(
(SELECT T1.ORDNO,T1.JOBNO,T1.FITEM FROM AMFLIBL.MOMAST T1 WHERE T1.CRDT 
BETWEEN  INT('1'||SUBSTR(TRIM(CHAR(CURRENT DATE - 180 DAYS)),3,2)||SUBSTR(TRIM(CHAR(CURRENT DATE- 180 DAYS)),6,2)||SUBSTR(TRIM(CHAR(CURRENT DATE- 180 DAYS)),9,2)) 
AND INT('1'||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),3,2)||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),6,2)||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),9,2)) 
ORDER BY T1.CRDT DESC) 
UNION ALL 
-- MOMAST ARCHIVED FILE IS MOHMST
(SELECT T1.ORDNO,T1.JOBNO,T1.FITEM FROM AMFLIBL.MOHMST T1 WHERE T1.CRDT 
BETWEEN  INT('1'||SUBSTR(TRIM(CHAR(CURRENT DATE - 180 DAYS)),3,2)||SUBSTR(TRIM(CHAR(CURRENT DATE- 180 DAYS)),6,2)||SUBSTR(TRIM(CHAR(CURRENT DATE- 180 DAYS)),9,2))  
AND INT('1'||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),3,2)||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),6,2)||SUBSTR(TRIM(CHAR(CURRENT DATE + 1 DAYS)),9,2)) 
ORDER BY T1.CRDT DESC)
) AS X2 
ON X1.MO=X2.ORDNO AND X1.TDITEM=X2.FITEM) AS Y1 

LEFT JOIN
-- SN IN SHIPPED CONTAINERS AND CONTAINERS' STATUS
(SELECT CHAR(TRIM(A.WCSSERIALNUMBER)) AS SN,A.WCSCONTAINERNUMBER AS CTN, 
(CASE 
	WHEN A.WCSCONTAINERNUMBER LIKE 'MRUN%' THEN 'INTEMPCTN' 
	WHEN A.WCSCONTAINERNUMBER LIKE 'KECR%' THEN 'INTEMPCTN' 
	WHEN A.WCSCONTAINERNUMBER LIKE 'KHO%' THEN 'INTEMPCTN' 
	WHEN A.WCSCONTAINERNUMBER LIKE 'M3K%' THEN 'INTEMPCTN' 
	WHEN A.WCSCONTAINERNUMBER LIKE 'M3E%' THEN 'INTEMPCTN' 
	WHEN A.WCSCONTAINERNUMBER LIKE 'M3H%' THEN 'INTEMPCTN' 
	WHEN A.WCSCONTAINERNUMBER LIKE 'RUN%' THEN 'INTEMPCTN' ELSE 'INREALCTN' END) AS "CTN_STATUS" 
	FROM LLUSAF.WVCNTSD A, LLUSAF.WVCNTHD B  
WHERE A.WCSCONTAINERNUMBER = B.WCHCONTAINERNUMBER AND B.WCHCONTAINERSTATUS NOT IN ('P','T')
) AS Y2 
ON Y1.SN = Y2.SN 
LIMIT 10