
SELECT ITEM#,SUM(CARTONS) AS "Cartons"
FROM 
(
SELECT a.WCICONTAINERNUMBER AS CONTAINER#, a.WCIORIGIN AS WH, a.WCIDESTINATION AS DESTINATION, a.WCIORDER as CO#, 
a.WCIITEMNUMBER AS ITEM#, a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP as LASTUPDATEDTIME, a.WCILASTMAINTENANCEUSER as USER, 
c.itcls,c.B2Z95S as UnitCube, c.WEGHT*a.WCIQUANTITYLOADED  as Weight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes, a.WCIQUANTITYLOADED/b.ITMCQTY as CARTONS,d.WCHBUILDING as Building,concat(d.WCHDOORNUMBER,d.WCHDOCKID) as Door

FROM LLUSAF.WVCNTID as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c, LLUSAF.WVCNTHD as d

WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51','52') and a.WCICONTAINERNUMBER = d.WCHCONTAINERNUMBER and d.WCHCONTAINERSTATUS in ('A','R') and 
a.WCICONTAINERNUMBER not LIKE 'KECR%'
and a.WCICONTAINERNUMBER not LIKE 'M3K%'
and a.WCICONTAINERNUMBER not LIKE 'M3E%'
and a.WCICONTAINERNUMBER not LIKE 'M3H%'
and a.WCICONTAINERNUMBER not LIKE 'KHO%'
and a.WCICONTAINERNUMBER not LIKE 'MRUN%'
and a.WCICONTAINERNUMBER not LIKE 'RUN%'
Order by a.WCICONTAINERNUMBER, a.WCIITEMNUMBER , a.WCIDESTINATION, a.WCIORDER
)
GROUP BY ITEM#