-- MIL OPEN MO BY P&IC, Created by Jimshen on Sep.28.2021


SELECT t1.STID, t1.ORDNO, t1.FITEM, t1.ORQTY+t1.QTDEV as MO_QTY, t1.QTYRC AS RECEIVED_QTY,t1.ORQTY+t1.QTDEV-t1.QTYRC AS OPEN_QTY,
t1.ODUDT,t1.ITCL, t1.JOBNO,t1.CRDT, t1.CRUS,
(CASE 
        WHEN t1.ITCL IN ('WPLS') THEN 'Plastics'
		WHEN t1.ITCL IN ('PANL') THEN 'Panel'
		WHEN t1.ITCL IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t1.ITCL IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t1.ITCL IN ('SLDK') THEN 'RP'
        WHEN t1.ITCL LIKE 'T%' THEN 'RP'
        WHEN t1.ITCL IN ('ZKIS') THEN 'Bedding'
		WHEN t1.ITCL IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCL LIKE 'Z%' AND t1.ITCL LIKE '%K' THEN 'UnKits'
		WHEN t1.ITCL IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCL IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCL IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCL LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM AMFLIBL.MOMAST t1
WHERE t1.ORQTY+t1.QTDEV <>0
AND t1.OSTAT in ('10','40','45') AND  t1.FITEM NOT LIKE '%VN%'
--AND t1.ODUDT between 1220101 AND 1221231 
ORDER BY t1.FITEM, t1.ODUDT, t1.ORDNO



-- WHERE SUBSTR(t1.ORDNO,1,2) In ('MX') AND t1.ORQTY+t1.QTDEV <>0
-- AND t1.OSTAT in ('10','40','45') AND  t1.FITEM NOT LIKE '%VN%'


-- another version

-- WANEK OPEN MO QUERY V02
SELECT MOMAST.STID, MOMAST.ORDNO, MOMAST.FITEM, MOMAST.ORQTY+MOMAST.QTDEV as MO_QTY, MOMAST.QTYRC AS RECEIVED_QTY,MOMAST.ORQTY+MOMAST.QTDEV-MOMAST.QTYRC AS OPEN_QTY,
MOMAST.ODUDT,MOMAST.ITCL, MOMAST.JOBNO,MOMAST.CRDT, MOMAST.CRUS
FROM AMFLIBL.MOMAST MOMAST
--WHERE SUBSTR(MOMAST.ORDNO,1,2) In ('MX','MU','MY') AND MOMAST.ORQTY+MOMAST.QTDEV <>0
WHERE  MOMAST.ITCL like 'Z%' AND MOMAST.ITCL NOT LIKE '%K' AND  MOMAST.ORQTY+MOMAST.QTDEV <>0

AND MOMAST.OSTAT in ('10','40','45') AND  MOMAST.FITEM NOT LIKE '%VN%'
--AND MOMAST.ODUDT between 1210801 AND 1210811 
ORDER BY MOMAST.FITEM, MOMAST.ODUDT, MOMAST.ORDNO