-- MIL STAGE REPORT 

SELECT *
FROM
( 
SELECT t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t4.B2Z95S as Cubes, t4.ITDSC, t4.WEGHT*t2.MOHTQ as Weight,
(CASE 
	WHEN t2.MOHTQ/t3.ITMCQTY IS NULL THEN t2.MOHTQ 
	WHEN t2.MOHTQ/t3.ITMCQTY<=1 THEN 1 
	ELSE ROUND(t2.MOHTQ/t3.ITMCQTY) END) as Cartons,
(CASE 
        WHEN t2.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t2.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t2.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t2.ITCLS IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t2.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t2.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t2.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t2.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t2.ITCLS LIKE 'Z%' AND t2.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t2.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t2.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t2.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t2.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product


FROM AFILELIBL.ITBEXT t1, AMFLIBL.ITEMBL t2, AFILELIBL.ITMEXT t3, AMFLIBL.ITMRVA t4

WHERE t1.ITNBR = t4.ITNBR AND t2.HOUSE = t1.HOUSE AND t2.ITNBR = t1.ITNBR AND t2.ITNBR = t4.ITNBR AND t2.ITCLS = t4.ITCLS AND t3.ITNBR = t1.ITNBR AND t3.ITNBR = t2.ITNBR AND t3.ITNBR = t4.ITNBR AND t4.STID = t1.HOUSE AND (t1.HOUSE='51') and t2.MOHTQ>0 and t2.WHSLC in ('FA00')
ORDER BY t4.ITNBR) AS X1

LEFT JOIN 
-- wnek open co 2021/9/27
(SELECT Item,
	SUM(CASE WHEN DESTINATION = '001' THEN CARTONS ELSE 0 END) AS "001",
	SUM(CASE WHEN DESTINATION = '1' THEN CARTONS ELSE 0 END) AS "Arcadia-1",
	SUM(CASE WHEN DESTINATION = '12' THEN CARTONS ELSE 0 END) AS "Ripley-12",
	SUM(CASE WHEN DESTINATION = '15' THEN CARTONS ELSE 0 END) AS "Leesport-15",
	SUM(CASE WHEN DESTINATION = '17' THEN CARTONS ELSE 0 END) AS "Advance-17",
	SUM(CASE WHEN DESTINATION = '19' THEN CARTONS ELSE 0 END) AS "Saltillo-19",
	SUM(CASE WHEN DESTINATION = '28' THEN CARTONS ELSE 0 END) AS "Mesquit-28",
	SUM(CASE WHEN DESTINATION = '335' THEN CARTONS ELSE 0 END) AS "Ashton-335",	
	SUM(CASE WHEN DESTINATION = '42' THEN CARTONS ELSE 0 END) AS "Tacoma-42",
	SUM(CASE WHEN DESTINATION = '5' THEN CARTONS ELSE 0 END) AS "Redlands-5",
	SUM(CASE WHEN DESTINATION = 'ECR' THEN CARTONS ELSE 0 END) AS ECR,
	SUM(CASE WHEN DESTINATION = 'C' THEN CARTONS ELSE 0 END) AS C,
	SUM(CASE WHEN DESTINATION = 'CNW' THEN CARTONS ELSE 0 END) AS CNW,
	SUM(CARTONS) AS "TotalOpenCO"
FROM 
(
SELECT a.CDA3CD as WH,a.CDCVNB as Order_Number,a.CDAITX as Item,a.CDD0NB as ETD,a.CDB9CD as Destination,a.CDAGNV as Qty,a.CDGLCD as itemclass,a.CDALTX as Description,a.CDAMDT as creationdate,a.CDAFVN,a.CDAGVN, round(a.CDAGNV/b.ITMCQTY) as Cartons

FROM AMFLIBL.MBCDRESM a, AFILELIBL.ITMEXT as b
WHERE CDAGNV >0 and a.CDAITX =b.ITNBR
order by a.CDD0NB, a.CDAITX
)
GROUP BY Item) as X2

ON X1.ITNBR = X2.Item



--------MIL  Un-SA containers item and q'ty
SELECT ITEM#,SUM(CARTONS) AS "Cartons"
FROM 
(
SELECT a.WCICONTAINERNUMBER AS CONTAINER#, a.WCIORIGIN AS WH, a.WCIDESTINATION AS DESTINATION, a.WCIORDER as CO#, 
a.WCIITEMNUMBER AS ITEM#, a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP as LASTUPDATEDTIME, a.WCILASTMAINTENANCEUSER as USER, 
c.itcls,c.B2Z95S as UnitCube, c.WEGHT*a.WCIQUANTITYLOADED  as Weight, a.WCIQUANTITYLOADED*c.B2Z95S as Cubes, a.WCIQUANTITYLOADED/b.ITMCQTY as CARTONS,d.WCHBUILDING as Building,concat(d.WCHDOORNUMBER,d.WCHDOCKID) as Door

FROM LLUSAF.WVCNTID as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c, LLUSAF.WVCNTHD as d

WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51','52') and a.WCICONTAINERNUMBER = d.WCHCONTAINERNUMBER and d.WCHCONTAINERSTATUS in ('A','R') and 
a.WCICONTAINERNUMBER not LIKE 'KECR%'
and a.WCICONTAINERNUMBER not LIKE 'M3K%'
and a.WCICONTAINERNUMBER not LIKE 'M3E%'
and a.WCICONTAINERNUMBER not LIKE 'M3H%'
and a.WCICONTAINERNUMBER not LIKE 'KHO%'
and a.WCICONTAINERNUMBER not LIKE 'MRUN%'
and a.WCICONTAINERNUMBER not LIKE 'RUN%'
Order by a.WCICONTAINERNUMBER, a.WCIITEMNUMBER , a.WCIDESTINATION, a.WCIORDER
)
GROUP BY ITEM#
