--MIL CO COMPLETION

select *
from
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, 
a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, 
a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
(CASE 
        When a.WCIDESTINATION in ('C','CNW','DS00009','TI00002') then trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||to_char(a.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') 
        ELSE trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) END) as Container#,
(CASE 
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN c.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN c.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM LLUSAF.WVCNTID as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c, LLUSAF.WVCNTHD as h
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51') and 
a.WCIORIGIN = h.WCHORIGIN and a.WCICONTAINERNUMBER=h.WCHCONTAINERNUMBER 
and  a.WCILASTMAINTENANCETIMESTAMP  between ? and ?  and h.WCHCONTAINERSTATUS in ('P','T') 
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)
union
(SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, 
a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, 
a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
(CASE 
        When a.WCIDESTINATION in ('C','CNW','DS00009','TI00002') then trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||to_char(a.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') 
        ELSE trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) END) as Container#,
(CASE 
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN c.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN c.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
FROM ASHLEYARCL.WVCNTIDA as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51') 
and a.WCILASTMAINTENANCETIMESTAMP  between ? and ?  AND substr(a.WCICONTAINERNUMBER,1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)) as x2
WHERE X2.WCIDESTINATION in ('C','CNW','DS00009','TI00002')
ORDER BY x2.WCILASTMAINTENANCETIMESTAMP, x2.WCIORDER,x2.CONTAINERNUMBER, x2.WCIORIGIN,x2.ITEMNUMBER,x2.WCIDESTINATION


--  QUERY BY CO#


select *
from
((SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, 
a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, 
a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
(CASE 
        When a.WCIDESTINATION in ('C','CNW','DS00009','TI00002') then trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||to_char(a.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') 
        ELSE trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) END) as Container#,
(CASE 
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN c.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN c.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM LLUSAF.WVCNTID as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c, LLUSAF.WVCNTHD as h
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51') and 
a.WCIORIGIN = h.WCHORIGIN and a.WCICONTAINERNUMBER=h.WCHCONTAINERNUMBER 
and  a.WCIORDER  = ? and h.WCHCONTAINERSTATUS in ('P','T') 
AND substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)
union
(SELECT trim(a.WCICONTAINERNUMBER) as ContainerNumber, a.WCIORIGIN, a.WCIDESTINATION, a.WCIORDER, trim(a.WCIITEMNUMBER) as ItemNumber, 
a.WCIQUANTITYLOADED as Qty, a.WCILASTMAINTENANCETIMESTAMP, a.WCILASTMAINTENANCEUSER, b.ITMCQTY, c.itcls,c.B2Z95S as UnitCube, c.WEGHT as UnitWeight, 
a.WCIQUANTITYLOADED*c.B2Z95S as Cubes,CEIL(a.WCIQUANTITYLOADED/b.ITMCQTY) as Cartons,
(CASE 
        When a.WCIDESTINATION in ('C','CNW','DS00009','TI00002') then trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION)||'-'||to_char(a.WCILASTMAINTENANCETIMESTAMP,'yyyy-mm-dd') 
        ELSE trim(a.WCIORIGIN)||'-'|| trim(a.WCICONTAINERNUMBER)||'-'||trim(a.WCIDESTINATION) END) as Container#,
(CASE 
        WHEN c.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN c.ITCLS IN ('PANL') THEN 'Panel'
		WHEN c.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN c.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN c.ITCLS IN ('SLDK') THEN 'RP'
        WHEN c.ITCLS LIKE 'T%' THEN 'RP'
        WHEN c.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN c.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN c.ITCLS LIKE 'Z%' AND c.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN c.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN c.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN c.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN c.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
FROM ASHLEYARCL.WVCNTIDA as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITMRVA as c
WHERE (a.WCIITEMNUMBER = b.itnbr) and a.WCIITEMNUMBER = c.itnbr and a.WCIORIGIN = c.STID and a.WCIORIGIN in('51') 
and a.WCIORDER = ? AND substr(a.WCICONTAINERNUMBER,1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_')
Order by a.WCICONTAINERNUMBER, a.WCIORIGIN, a.WCILASTMAINTENANCETIMESTAMP, a.WCIDESTINATION)) as x2
WHERE X2.WCIDESTINATION in ('C','CNW','DS00009','TI00002')
ORDER BY x2.WCILASTMAINTENANCETIMESTAMP, x2.WCIORDER,x2.CONTAINERNUMBER, x2.WCIORIGIN,x2.ITEMNUMBER,x2.WCIDESTINATION