
-- sheet 0642 by MO
SELECT UDDSTS,UDDMOR,UDDITM,UDDSER,UDDWRK, UDDDAT,UDDTIM,UDDUSR,UDDPGM,UDMDAT,UDMTIM,UDMUSR,UDMPGM,UDVDAT,UDVTIM,
UDVUSR,UDVPGM,UDCDAT,UDCTIM,UDCUSR,UDCPGM,
(CASE WHEN TDTSTS = 'S' or TDTSTS = 'T' THEN TDMDAT  ELSE 0 END) AS SHIPDATE, 
(CASE WHEN TDTSTS = 'S' or TDTSTS = 'T' THEN TDMTME  ELSE 0 END) AS SHIPTIME
From LLUSAF.DWUPHSCND DWUPHSCND, DISTLIBL.TAGINVD TAGINVD
Where UDDMOR=? and UDDDAT between 20200101 and 20291231 and DWUPHSCND.UDDSER=TAGINVD.TDTAG#
Order by UDDDAT,UDDTIM,UDDMOR,UDDITM,UDDSER


-- sheet 0642 by WMS=0
SELECT UDDSTS,UDDMOR,UDDITM,UDDSER,UDDWRK, UDDDAT,UDDTIM,UDDUSR,UDDPGM,UDMDAT,UDMTIM,UDMUSR,UDMPGM,UDVDAT,UDVTIM,            
UDVUSR,UDVPGM,UDCDAT,UDCTIM,UDCUSR,UDCPGM,
(CASE WHEN TDTSTS = 'S' or TDTSTS = 'T' THEN TDMDAT  ELSE 0 END) AS SHIPDATE, 
(CASE WHEN TDTSTS = 'S' or TDTSTS = 'T' THEN TDMTME  ELSE 0 END) AS SHIPTIME
From LLUSAF.DWUPHSCND DWUPHSCND, DISTLIBL.TAGINVD TAGINVD
Where UDDDAT between ? and ? and (CASE WHEN TDTSTS = 'S' or TDTSTS = 'T' THEN TDMDAT  ELSE 0 END)=0 and DWUPHSCND.UDDSER=TAGINVD.TDTAG#
Order by UDDMOR,UDDITM,UDDSER,UDDDAT,UDDTIM