
SELECT m1.STID,	m1.ORDNO,	m1.FITEM,	m1.PRODUCT,	m1.MO_QTY,	m1.RECEIVED_QTY,	m1.OPEN_QTY,	m1.ODUDT,	m1.ITCL,	m1.JOBNO,	m1.CRDT,	m1.CRUS,	s1.WCSITEMNUMBER,	s1.TDAPO#,	s1.SA_QTY, m1.MO_QTY-s1.SA_QTY AS GAP

FROM
(
--MO information
(SELECT t1.STID, t1.ORDNO, t1.FITEM, t1.ORQTY+t1.QTDEV as MO_QTY, t1.QTYRC AS RECEIVED_QTY,t1.ORQTY+t1.QTDEV-t1.QTYRC AS OPEN_QTY,
t1.ODUDT,t1.ITCL, t1.JOBNO,t1.CRDT, t1.CRUS,
(CASE 
        WHEN t1.ITCL IN ('WPLS') THEN 'Plastics'
		WHEN t1.ITCL IN ('PANL') THEN 'Panel'
		WHEN t1.ITCL IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t1.ITCL IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t1.ITCL IN ('SLDK') THEN 'RP'
        WHEN t1.ITCL LIKE 'T%' THEN 'RP'
        WHEN t1.ITCL IN ('ZKIS') THEN 'Bedding'
		WHEN t1.ITCL IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCL LIKE 'Z%' AND t1.ITCL LIKE '%K' THEN 'UnKits'
		WHEN t1.ITCL IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCL IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCL IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCL LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM AMFLIBL.MOMAST t1
WHERE t1.ORQTY+t1.QTDEV <>0
--AND t1.OSTAT in ('10','40','45') 
AND t1.ODUDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 90 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
ORDER BY t1.FITEM, t1.ODUDT, t1.ORDNO)

UNION ALL

(SELECT t1.STID, t1.ORDNO, t1.FITEM, t1.ORQTY+t1.QTDEV as MO_QTY, t1.QTYRC AS RECEIVED_QTY,t1.ORQTY+t1.QTDEV-t1.QTYRC AS OPEN_QTY,
t1.ODUDT,t1.ITCL, t1.JOBNO,t1.CRDT, t1.CRUS,
(CASE 
        WHEN t1.ITCL IN ('WPLS') THEN 'Plastics'
		WHEN t1.ITCL IN ('PANL') THEN 'Panel'
		WHEN t1.ITCL IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t1.ITCL IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t1.ITCL IN ('SLDK') THEN 'RP'
        WHEN t1.ITCL LIKE 'T%' THEN 'RP'
        WHEN t1.ITCL IN ('ZKIS') THEN 'Bedding'
		WHEN t1.ITCL IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCL LIKE 'Z%' AND t1.ITCL LIKE '%K' THEN 'UnKits'
		WHEN t1.ITCL IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCL IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCL IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCL LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM AMFLIBL.MOHMST t1
WHERE t1.ORQTY+t1.QTDEV <>0
--AND t1.OSTAT in ('10','40','45') 
AND t1.ODUDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 90 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
ORDER BY t1.FITEM, t1.ODUDT, t1.ORDNO)
) as m1

LEFT JOIN
		-- CURRENT AND ARCHIVED F/G SN SA done
		((SELECT a.WCSITEMNUMBER,c.TDAPO#, COUNT(CHAR(trim(a.WCSSERIALNUMBER))) AS SA_QTY
			FROM LLUSAF.WVCNTSD a, LLUSAF.WVCNTHD b, DISTLIBL.TAGINVD c
			WHERE a.WCSCONTAINERNUMBER = b.WCHCONTAINERNUMBER AND a.WCSSERIALNUMBER = c.TDTAG# and a.WCSITEMNUMBER = c.TDITEM and b.WCHCONTAINERSTATUS IN ('P','T') AND b.WCHPOSTEDTIMESTAMP BETWEEN CHAR(CURRENT DATE - 91 days) AND CHAR(CURRENT DATE + 1 days)
			GROUP BY a.WCSITEMNUMBER,c.TDAPO#)
		UNION ALL
 
			-- Archived container serial numbers in past 90 days
		(SELECT a.WCSITEMNUMBER,c.TDAPO#, COUNT(CHAR(trim(a.WCSSERIALNUMBER))) AS SA_QTY
			FROM ASHLEYARCL.WVCNTSDA a, DISTLIBL.TAGINVD c
			WHERE a.WCSSERIALNUMBER = c.TDTAG# and a.WCSITEMNUMBER = c.TDITEM  AND 
			a.WCSADDEDTIMESTAMP between char(current date - 91 days) and char(current DATE + 1 days)
			GROUP BY a.WCSITEMNUMBER,c.TDAPO#))  as s1 
ON m1.ORDNO = s1.TDAPO# AND m1.FITEM = s1.WCSITEMNUMBER
WHERE m1.FITEM = ? AND m1.MO_QTY-s1.SA_QTY <>0
