-- MIL Shipping Query SQL v02  added shift

-- V03

SELECT a.WCSCONTAINERNUMBER, a.WCSORIGIN, a.WCSDESTINATION,a.WCSITEMNUMBER, a.WCSADDEDUSER, b.ITMCQTY,count(a.WCSSERIALNUMBER) as Qty, t3.itcls,
(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product,
(CASE WHEN char(substr(char(TIME(a.WCSADDEDTIMESTAMP)),1,2)||substr(char(TIME(a.WCSADDEDTIMESTAMP)),4,2)||
substr(char(TIME(a.WCSADDEDTIMESTAMP)),7,2)) BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END) AS SHIFT


FROM LLUSAF.TBL_WVCONTAINER_DTL_SER as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITEMBL t3 
WHERE (a.WCSITEMNUMBER = b.itnbr) and a.WCSCONTAINERNUMBER NOT LIKE  'KHOA%' and a.WCSCONTAINERNUMBER NOT LIKE  'KECR%' 
and a.WCSCONTAINERNUMBER NOT LIKE  'M3%' 
AND a.WCSADDEDTIMESTAMP  between ? and ? and a.WCSORIGIN=t3.HOUSE and a.WCSITEMNUMBER = t3.itnbr and b.itnbr=t3.itnbr

Group by a.WCSCONTAINERNUMBER,a.WCSORIGIN, a.WCSDESTINATION, a.WCSITEMNUMBER,a.WCSADDEDUSER,b.ITMCQTY,t3.itcls,
(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END),
(CASE WHEN char(substr(char(TIME(a.WCSADDEDTIMESTAMP)),1,2)||substr(char(TIME(a.WCSADDEDTIMESTAMP)),4,2)||
substr(char(TIME(a.WCSADDEDTIMESTAMP)),7,2)) BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END)

Order by a.WCSCONTAINERNUMBER



--substr(trim(a.WCICONTAINERNUMBER),1,4) NOT IN ('AAAR','AIIR','AAIR','AIRR','AIR_','AIR1') and  


--- CONTAINER SHIPPED BY SN 
SELECT a.WCSCONTAINERNUMBER, a.WCSORIGIN, a.WCSDESTINATION,a.WCSITEMNUMBER, a.WCSADDEDUSER, b.ITMCQTY, CHAR(a.WCSSERIALNUMBER) as SN, t3.itcls, 
CHAR(a.WCSADDEDTIMESTAMP) AS DATETIME, 
(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product,
(CASE WHEN char(substr(char(TIME(a.WCSADDEDTIMESTAMP)),1,2)||substr(char(TIME(a.WCSADDEDTIMESTAMP)),4,2)||substr(char(TIME(a.WCSADDEDTIMESTAMP)),7,2)) BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END) AS SHIFT

FROM LLUSAF.TBL_WVCONTAINER_DTL_SER as a, AFILELIBL.ITMEXT as b, AMFLIBL.ITEMBL t3 
   
WHERE (a.WCSITEMNUMBER = b.itnbr) and a.WCSCONTAINERNUMBER NOT LIKE  'KHOA%' and a.WCSCONTAINERNUMBER NOT LIKE  'KECR%' and a.WCSCONTAINERNUMBER NOT LIKE  'M3%' 
AND a.WCSADDEDTIMESTAMP  between ? and ? and a.WCSORIGIN=t3.HOUSE and a.WCSITEMNUMBER = t3.itnbr and b.itnbr=t3.itnbr
Order by a.WCSCONTAINERNUMBER







