SELECT A. BXDCOMPONENTITEMNUMBER, A. BXDCOMPONENTITEMCLASS, A. BXDPARENTITEMNUMBER, A. BXDPARENTITEMCLASS
FROM RGNFILL.PSTBOMD A
Where  A.BXDSTID = '51'



SELECT *
FROM RGNFILL.PSTBOMD T1
Where  TRIM(T1.BXDPARENTITEMNUMBER) LIKE '%UN' AND (T1.BXDCOMPONENTITEMDESCRIPTION LIKE 'RSC%'  OR  T1.BXDCOMPONENTITEMDESCRIPTION  LIKE  'UWALL%')
LIMIT 100

