-- MIL ITEM,MO,SA query, created on Jan.15.2022 by JimShen

-- Pullout SN generated
SELECT *
FROM
(
SELECT x1.ITCLS,x1.PRODUCT,x1.SN,x1.TDITEM,x1.MO,x1.TDMDAT,x1.TDTSTS,x1.TXT_TIME,x1.ITMCQTY,x1.SHIFT,s1.WCSCONTAINERNUMBER,s1.WCSDESTINATION,s1.WCSORDER,s1.WCSADDEDTIMESTAMP
FROM 
(SELECT CHAR(trim(t1.TDTAG#)) AS SN,t1.TDITEM,t1.TDAPO# as MO,t1.TDWHSE,t1.TDMDAT,t1.TDMTME,
t1.TDTSTS,right('000000'||ltrim(t1.TDMTME),6) AS TXT_TIME,t3.ITCLS,t5.ITMCQTY,
(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t3.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'FR SOCK'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product,
(CASE WHEN t1.TDMTME BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END) AS SHIFT


FROM DISTLIBL.TAGINVD t1,(SELECT DISTINCT t2.ITNBR,t2.ITCLS FROM AMFLIBL.ITEMBL t2 WHERE t2.HOUSE = '51' GROUP BY t2.ITNBR,t2.ITCLS) AS t3,
(SELECT DISTINCT t4.ITNBR,t4.ITMCQTY FROM AFILELIBL.ITMEXT t4 GROUP BY t4.ITNBR,t4.ITMCQTY) AS t5

WHERE t1.TDITEM = t3.ITNBR AND t1.TDITEM=t5.ITNBR AND t3.ITNBR=t5.ITNBR and t1.TDMDAT 
BETWEEN  int('1'||substr(trim(char(CURRENT DATE - 90 days)),3,2)||substr(trim(char(CURRENT DATE- 90 days)),6,2)||substr(trim(char(CURRENT DATE- 90 days)),9,2)) 
AND int('1'||substr(trim(char(CURRENT DATE + 1 days)),3,2)||substr(trim(char(CURRENT DATE + 1 days)),6,2)||substr(trim(char(CURRENT DATE + 1 days)),9,2))
and t1.TDITEM = ?) x1

LEFT JOIN 

		-- CURRENT AND ARCHIVED F/G SN SA done
		((SELECT CHAR(trim(a.WCSSERIALNUMBER)) AS SN, a.WCSITEMNUMBER,a.WCSCONTAINERNUMBER,a.WCSDESTINATION,a.WCSORDER,a.WCSADDEDTIMESTAMP
			FROM LLUSAF.WVCNTSD a, LLUSAF.WVCNTHD b 
			WHERE a.WCSCONTAINERNUMBER = b.WCHCONTAINERNUMBER and b.WCHCONTAINERSTATUS IN ('P','T') AND b.WCHPOSTEDTIMESTAMP BETWEEN CHAR(CURRENT DATE - 91 days) AND CHAR(CURRENT DATE + 1 days))
		UNION ALL
 
			-- Archived container serial numbers in past 90 days
		(SELECT CHAR(TRIM(a.WCSSERIALNUMBER)) AS SN, a.WCSITEMNUMBER,a.WCSCONTAINERNUMBER,a.WCSDESTINATION,a.WCSORDER,a.WCSADDEDTIMESTAMP
			FROM ASHLEYARCL.WVCNTSDA a
			WHERE a.WCSADDEDTIMESTAMP between char(current date - 91 days) and char(current DATE + 1 days)))  as s1 
		ON x1.SN = s1.SN 
) as s2


LEFT JOIN

((SELECT t1.STID, t1.ORDNO, t1.FITEM, t1.ORQTY+t1.QTDEV as MO_QTY, t1.QTYRC AS RECEIVED_QTY,t1.ORQTY+t1.QTDEV-t1.QTYRC AS OPEN_QTY,
t1.ODUDT,t1.ITCL, t1.JOBNO,t1.CRDT, t1.CRUS,
(CASE 
        WHEN t1.ITCL IN ('WPLS') THEN 'Plastics'
		WHEN t1.ITCL IN ('PANL') THEN 'Panel'
		WHEN t1.ITCL IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t1.ITCL IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t1.ITCL IN ('SLDK') THEN 'RP'
        WHEN t1.ITCL LIKE 'T%' THEN 'RP'
        WHEN t1.ITCL IN ('ZKIS') THEN 'Bedding'
		WHEN t1.ITCL IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCL LIKE 'Z%' AND t1.ITCL LIKE '%K' THEN 'UnKits'
		WHEN t1.ITCL IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCL IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCL IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCL LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM AMFLIBL.MOMAST t1
WHERE t1.ORQTY+t1.QTDEV <>0
--AND t1.OSTAT in ('10','40','45') 
AND t1.ODUDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 90 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
ORDER BY t1.FITEM, t1.ODUDT, t1.ORDNO)

UNION ALL

(SELECT t1.STID, t1.ORDNO, t1.FITEM, t1.ORQTY+t1.QTDEV as MO_QTY, t1.QTYRC AS RECEIVED_QTY,t1.ORQTY+t1.QTDEV-t1.QTYRC AS OPEN_QTY,
t1.ODUDT,t1.ITCL, t1.JOBNO,t1.CRDT, t1.CRUS,
(CASE 
        WHEN t1.ITCL IN ('WPLS') THEN 'Plastics'
		WHEN t1.ITCL IN ('PANL') THEN 'Panel'
		WHEN t1.ITCL IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t1.ITCL IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t1.ITCL IN ('SLDK') THEN 'RP'
        WHEN t1.ITCL LIKE 'T%' THEN 'RP'
        WHEN t1.ITCL IN ('ZKIS') THEN 'Bedding'
		WHEN t1.ITCL IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCL LIKE 'Z%' AND t1.ITCL LIKE '%K' THEN 'UnKits'
		WHEN t1.ITCL IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCL IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCL IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCL LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
		
FROM AMFLIBL.MOHMST t1
WHERE t1.ORQTY+t1.QTDEV <>0
--AND t1.OSTAT in ('10','40','45') 
AND t1.ODUDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 90 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
ORDER BY t1.FITEM, t1.ODUDT, t1.ORDNO)
) as m1
ON s2.MO=m1.ORDNO and s2.TDITEM = m1.FITEM

