
SELECT  x1.WSCWAREHOUSE, x1.WSCWEEKENDINGDATE, x1.WSCDUEDATE, x1.WSCLINENUMBER, x1.WSCITEMNUMBER, x1.WSCQUANTITY, x1.WSCMAPICSMNUMBER, x1.Code, x1.P_schedule, x1.S_Schedule,
x1.Qty_Ship as QTY_SA, y1.TRQTY as QTY_RM 
FROM
-- Org MSS
(SELECT t1.WSCWAREHOUSE, t1.WSCWEEKENDINGDATE, t1.WSCDUEDATE, t1.WSCLINENUMBER, t1.WSCITEMNUMBER, t1.WSCQUANTITY, t1.WSCMAPICSMNUMBER,  t1.Code, t1.P_schedule, t1.S_Schedule,
t2.Qty_Ship
FROM
(
SELECT a.WSCWAREHOUSE, a.WSCWEEKENDINGDATE, a.WSCDUEDATE, a.WSCLINENUMBER, a.WSCITEMNUMBER, a.WSCQUANTITY, a.WSCMAPICSMNUMBER,  a.WSCMAPICSMNUMBER||a.WSCITEMNUMBER AS Code,
a.WSCWEEKENDINGDATE as P_schedule, a.WSCDUEDATE as S_Schedule
FROM LLUSAF.PC216WSCH a 
WHERE a.WSCMAPICSMNUMBER Like 'MM%' AND a.WSCWEEKENDINGDATE >= (CURRENT DATE - 10 days)
GROUP BY a.WSCWAREHOUSE, a.WSCWEEKENDINGDATE, a.WSCDUEDATE, a.WSCLINENUMBER, a.WSCITEMNUMBER, a.WSCQUANTITY, a.WSCMAPICSMNUMBER
) t1

LEFT JOIN

(SELECT t3.TDAPO#, t3.WCSITEMNUMBER,SUM(t3.QTY_SHIP) AS QTY_SHIP  FROM
(
--SHIP:  最近一周集装箱出货资料 与 tag的SN，MO连接，取得出资料存于SHIP sheet
SELECT a.TDAPO#,b.WCSITEMNUMBER, substr(char(b.WCSADDEDTIMESTAMP),1,10) as SA_Date, count(a.TDAPO#) as Qty_Ship
FROM DISTLIBL.TAGINVD1 a, LLUSAF.TBL_WVCONTAINER_DTL_SER b
WHERE b.WCSITEMNUMBER = a.TDITEM AND b.WCSSERIALNUMBER = a.TDTAG# AND b.WCSORIGIN In ('51') AND substr(a.TDAPO#,1,2) in ('MM') 
and b.WCSADDEDTIMESTAMP >= (CURRENT DATE - 40 days)
GROUP BY a.TDAPO#, b.WCSITEMNUMBER, substr(char(b.WCSADDEDTIMESTAMP),1,10)

UNION ALL

-- SHIP NEW
SELECT a.RPLORDERNUMBER as Order, a.RPLITEMNUMBER as Item, substr(char(a.RPLLOADDATE),1,10) as SA_Date,
a.RPLPRINTQUANTITY as Qty_Ship 
FROM RGNFILL.PC228RPF a 
WHERE substr(a.RPLORDERNUMBER,1,2) in ('MM') 
and a.RPLLOADDATE >= (CURRENT DATE - 40 days) and RPLLOADSTATUS in ('S')
) t3
GROUP BY t3.TDAPO#, t3.WCSITEMNUMBER
) t2 
ON t1.WSCITEMNUMBER = t2.WCSITEMNUMBER and t1.WSCMAPICSMNUMBER = t2.TDAPO#
) x1

LEFT JOIN


(SELECT b1.ORDNO, b1.ITNBR, sum(b1.TRQTY) as TRQTY

FROM 
-- RM
(SELECT a.TRMID,a.TCODE,a.ORDNO,a.ITNBR,a.HOUSE,a.UPDDT,a.TRQTY 
FROM AMFLIBL.IMHIST a 
WHERE TCODE in ('RM') and substr(ORDNO,1,2) in ('MM') and UPDDT > CHAR('1'||VARCHAR_FORMAT(current date - 40 Days,'YYMMDD'))
) b1
GROUP BY b1.ORDNO, b1.ITNBR
) y1
ON x1.WSCMAPICSMNUMBER = y1.ORDNO and x1.WSCITEMNUMBER = y1.ITNBR
ORDER BY x1.WSCWEEKENDINGDATE