Select t1.ITNBR, t1.HOUSE, t1.MOHTQ, t1.WHSLC, t1.ITCLS, t1.QTSYR, t1.B2Z95S, 
t1.ITDSC, t1.TIHIUNLD, t1.PICKPUT, t1.ITMCLSID, t1.UNITSWIDE, t1.UNITLAYERS, t1.UNITSDEEP, 
t1.SCOOPQTY, t1.SKIDSIZE, t1.QTYCR, t1.NBSEAT, t1.CRTWIN, t1.CRTLIN, t1.CRTHIN, t1.PRDWIN, t1.PRDHIN, 
t1.PRDLIN, t1.ITMWEGHT,t2.Open_CO_Qty
from 

(SELECT ITMEXT.ITNBR as Item#,ITEMBL.ITNBR, ITEMBL.HOUSE, ITEMBL.MOHTQ, ITEMBL.WHSLC, ITEMBL.ITCLS, ITEMBL.QTSYR, ITMRVA.B2Z95S, 
ITMRVA.ITDSC, ITBEXT.TIHIUNLD, ITBEXT.PICKPUT, ITBEXT.ITMCLSID, ITBEXT.UNITSWIDE, ITBEXT.UNITLAYERS, ITBEXT.UNITSDEEP, ITBEXT.SCOOPQTY, 
ITBEXT.SKIDSIZE, ITMEXT.QTYCR, ITMEXT.NBSEAT, ITMEXT.CRTWIN, ITMEXT.CRTLIN, ITMEXT.CRTHIN, ITMEXT.PRDWIN, ITMEXT.PRDHIN, ITMEXT.PRDLIN, 
ITMEXT.ITMWEGHT
FROM AFILELIBL.ITBEXT ITBEXT, AMFLIBL.ITEMBL ITEMBL, AFILELIBL.ITMEXT ITMEXT, AMFLIBL.ITMRVA ITMRVA
WHERE ITBEXT.ITNBR = ITMRVA.ITNBR AND ITEMBL.HOUSE = ITBEXT.HOUSE AND ITEMBL.ITNBR = ITBEXT.ITNBR AND ITEMBL.ITNBR = ITMRVA.ITNBR 
AND ITEMBL.ITCLS = ITMRVA.ITCLS AND ITMEXT.ITNBR = ITBEXT.ITNBR AND ITMEXT.ITNBR = ITEMBL.ITNBR AND ITMEXT.ITNBR = ITMRVA.ITNBR 
AND ITMRVA.STID = ITBEXT.HOUSE AND (ITBEXT.HOUSE IN ('51')) AND (ITEMBL.ITCLS like 'Z%' and ITEMBL.ITCLS not like '%K')) as T1, 

(SELECT CDA3CD as MIL,CDAITX as item,CDGLCD as ItemClass, sum(CDAGNV) as Open_CO_Qty  
FROM AMFLIBL.MBCDRESM MBCDRESM  
WHERE CDAGNV >0 and CDGLCD like 'Z%' and CDGLCD not like '%K' 
Group by  CDA3CD,CDAITX,CDGLCD) AS T2 

where T1.Item# = T2.item and T1.HOUSE=T2.MIL and T1.ITCLS = T2.ItemClass
