-- MIL AS400 STOCK BY CARTONS  - 20211210 

SELECT t2.ITNBR, t1.ITDSC, t1.ITCLS,
(CASE 
        WHEN t1.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t1.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t1.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t1.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t1.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t1.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCLS LIKE 'Z%' AND t1.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t1.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'RawMaterial' END) AS Product,
       SUM(CASE WHEN t2.LLOCN IN ('FA00') AND t2.HOUSE in ('51') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH51_FA00,
       SUM(CASE WHEN t2.LLOCN NOT IN ('FA00') AND t2.HOUSE in ('51') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH51_Non_FA00,
	   SUM(CASE WHEN t2.LLOCN IN ('FA00') AND t2.HOUSE in ('52') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH52_FA00,
       SUM(CASE WHEN t2.LLOCN NOT IN ('FA00') AND t2.HOUSE in ('52') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH52_Non_FA00
	   
FROM AMFLIBL.ITEMASA t1, AMFLIBL.SLQNTY t2,AFILELIBL.ITMEXT t3
WHERE t1.ITNBR = t2.ITNBR and t2.ITNBR = t3.ITNBR
GROUP BY t2.ITNBR, t1.ITDSC, t1.ITCLS
HAVING (t1.ITCLS LIKE 'Z%' AND t1.ITCLS LIKE '%K') or t1.ITCLS IN ('PACS')
ORDER BY t2.ITNBR



















































-- MIL AS400 STOCK by ROW  - 20211106 

SELECT t2.ITNBR, t1.ITDSC, t1.ITCLS,
(CASE 
        WHEN t1.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t1.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t1.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t1.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t1.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t1.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCLS LIKE 'Z%' AND t1.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t1.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'RawMaterial' END) AS Product,
       SUM(CASE WHEN t2.LLOCN IN ('FA00') AND t2.HOUSE in ('51') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH51_FA00,
       SUM(CASE WHEN t2.LLOCN NOT IN ('FA00') AND t2.HOUSE in ('51') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH51_Non_FA00,
	   SUM(CASE WHEN t2.LLOCN IN ('FA00') AND t2.HOUSE in ('52') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH52_FA00,
       SUM(CASE WHEN t2.LLOCN NOT IN ('FA00') AND t2.HOUSE in ('52') THEN CEIL(t2.LQNTY/t3.ITMCQTY) ELSE 0 END) AS WH52_Non_FA00
	   
FROM AMFLIBL.ITEMASA t1, AMFLIBL.SLQNTY t2,AFILELIBL.ITMEXT t3
WHERE t1.ITNBR = t2.ITNBR and t2.ITNBR = t3.ITNBR
GROUP BY t2.ITNBR, t1.ITDSC, t1.ITCLS
HAVING t1.ITCLS LIKE 'Z%' AND t1.ITCLS LIKE '%K' AND t1.ITCLS IN ('PACS')
ORDER BY t2.ITNBR



-- MIL AS400 STOCK BY COLUMNS  - 20210813

SELECT t2.ITNBR, t1.ITDSC, t1.ITCLS, t2.HOUSE, t2.LLOCN, t2.FDATE, t2.LQNTY  "OnHand", t2.ORDNO, t2.LBHNO,CEIL(t2.LQNTY/t3.ITMCQTY) cartons,
(CASE 
        WHEN t1.ITCLS IN ('WPLS') THEN 'Plastics'
        WHEN t1.ITCLS IN ('WVBC','WVHC') THEN 'Foundation'
        WHEN t1.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t1.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t1.ITCLS IN ('ZKIS') THEN 'Bedding'
        WHEN t1.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t1.ITCLS LIKE 'Z%' AND t1.ITCLS LIKE '%K' THEN 'UnKits'
        WHEN t1.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t1.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t1.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t1.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'RawMaterial' END) AS Product
		
FROM AMFLIBL.ITEMASA t1, AMFLIBL.SLQNTY t2,AFILELIBL.ITMEXT t3
WHERE t1.ITNBR = t2.ITNBR and t2.ITNBR = t3.ITNBR AND ((t2.HOUSE='51') OR (t2.HOUSE='52'))


