-- MIL TRX Details 
SELECT t1.TCODE, t1.ORDNO, t1.ITNBR, t2.ITCLS, t1.HOUSE, t1.UPDDT, t1.UPDTM, t1.TRQTY, t1.LLOCN,t1.TRNDT, t1.LBHNO, t1.REFNO, t1.REASN, t1.USRSQ,t4.ITMCQTY
FROM AMFLIBL.IMHIST t1, AMFLIBL.ITMRVA t2, AMFLIBL.WHSMST t3, AFILELIBL.ITMEXT t4
WHERE ITMRVA.ITNBR = t1.ITNBR and t1.itnbr=t4.itnbr AND ITMRVA.STID = t3.STID AND t1.HOUSE = t3.WHID AND ((t1.HOUSE='51') AND (t1.UPDDT>=? And t1.UPDDT<=?) AND (t1.TRQTY<>0)) and t1.tcode in ('IP','PQ','RM','SA','RP','RS','IS','IA','VR')



-- MIL TRX Summary by week V02
SELECT t1.TCODE, t1.ITNBR, t2.ITCLS, t1.HOUSE, WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS WEEK, 
'20'||SUBSTR(CHAR(T1.UPDDT),2,2)*100+WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS "YearWeek", SUM(t1.TRQTY) AS Qty

FROM AMFLIBL.IMHIST t1, AMFLIBL.ITMRVA t2, AMFLIBL.WHSMST t3, AFILELIBL.ITMEXT t4
WHERE t2.ITNBR = t1.ITNBR and t1.itnbr=t4.itnbr AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND t1.HOUSE IN ('51','52') 
AND t1.UPDDT BETWEEN CHAR('1'||VARCHAR_FORMAT(CURRENT DATE - 90 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(CURRENT DATE,'YYMMDD')) AND t1.TRQTY<>0 AND t1.tcode IN ('IP','PQ','RM','SA','RP','RS','IS','IA','VR','IU','RC','SC','SM','SP','SS','LA')
GROUP BY  t1.TCODE, t1.ITNBR, t2.ITCLS, t1.HOUSE, WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))),
'20'||SUBSTR(CHAR(T1.UPDDT),2,2)*100+WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) 





-- MIL TRX Summary by week V01
SELECT t1.TCODE, t1.ITNBR, t2.ITCLS, t1.HOUSE, WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS WEEK, 
'20'||SUBSTR(CHAR(T1.UPDDT),2,2)*100+WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS "YearWeek", SUM(t1.TRQTY) AS Qty

FROM AMFLIBL.IMHIST t1, AMFLIBL.ITMRVA t2, AMFLIBL.WHSMST t3, AFILELIBL.ITMEXT t4
WHERE t2.ITNBR = t1.ITNBR and t1.itnbr=t4.itnbr AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND ((t1.HOUSE='51') 
AND t1.UPDDT BETWEEN CHAR('1'||VARCHAR_FORMAT(CURRENT DATE - 120 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(CURRENT DATE,'YYMMDD')) AND (t1.TRQTY<>0)) AND t1.tcode IN ('IP','PQ','RM','SA','RP','RS','IS','IA','VR','IU','RC','SC','SM','SP','SS','LA')
GROUP BY  t1.TCODE, t1.ITNBR, t2.ITCLS, t1.HOUSE, WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))),
'20'||SUBSTR(CHAR(T1.UPDDT),2,2)*100+WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) 





-- MIL TRX Summary
DECLARE v_Month as INTEGER

SELECT t1.TCODE, t1.ORDNO, t1.ITNBR, t2.ITCLS, t1.HOUSE, t1.UPDDT, t4.ITMCQTY,
(CASE 
        WHEN t2.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t2.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t2.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'
        WHEN t2.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t2.ITCLS LIKE 'T%' THEN 'RP'
		WHEN t2.ITCLS LIKE 'R%' THEN 'RP'
        WHEN t2.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t2.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t2.ITCLS LIKE 'Z%' AND t2.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t2.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t2.ITCLS IN ('BBFR','WVHC') THEN 'Verona'
        WHEN t2.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t2.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC') THEN 'UPH'
        ELSE 'RawMaterial' END) AS Product,
SUM(t1.TRQTY) AS Qty

FROM AMFLIBL.IMHIST t1, AMFLIBL.ITMRVA t2, AMFLIBL.WHSMST t3, AFILELIBL.ITMEXT t4
WHERE t2.ITNBR = t1.ITNBR and t1.itnbr=t4.itnbr AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND ((t1.HOUSE='51') 
AND t1.UPDDT BETWEEN CHAR('1'||VARCHAR_FORMAT(CURRENT DATE - 1 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(CURRENT DATE,'YYMMDD')) AND (t1.TRQTY<>0)) AND t1.tcode IN ('IP','PQ','RM','SA','RP','RS','IS','IA','VR','IU','RC','SC','SM','SP','SS','LA')
GROUP BY  t1.TCODE,t1.ORDNO, t1.ITNBR, t2.ITCLS, t1.HOUSE, t1.UPDDT, t4.ITMCQTY,
(CASE 
        WHEN t2.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t2.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t2.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'
        WHEN t2.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t2.ITCLS LIKE 'T%' THEN 'RP'
		WHEN t2.ITCLS LIKE 'R%' THEN 'RP'
        WHEN t2.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t2.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t2.ITCLS LIKE 'Z%' AND t2.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t2.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t2.ITCLS IN ('BBFR','WVHC') THEN 'Verona'
        WHEN t2.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t2.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC') THEN 'UPH'
        ELSE 'RawMaterial' END)



-- ITEM & Product
SELECT t1.ITNBR, t2.ITCLS, t1.HOUSE,
(CASE 
        WHEN t2.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t2.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t2.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'
        WHEN t2.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t2.ITCLS LIKE 'T%' THEN 'RP'
		WHEN t2.ITCLS LIKE 'R%' THEN 'RP'
        WHEN t2.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t2.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t2.ITCLS LIKE 'Z%' AND t2.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t2.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t2.ITCLS IN ('BBFR','WVHC') THEN 'Verona'
        WHEN t2.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t2.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC') THEN 'UPH'
        ELSE 'RawMaterial' END) AS Product,
SUM(t1.TRQTY) AS Qty

FROM AMFLIBL.IMHIST t1, AMFLIBL.ITMRVA t2, AMFLIBL.WHSMST t3, AFILELIBL.ITMEXT t4
WHERE t2.ITNBR = t1.ITNBR and t1.itnbr=t4.itnbr AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND ((t1.HOUSE='51') 
AND t1.UPDDT BETWEEN CHAR('1'||VARCHAR_FORMAT(CURRENT DATE - 1 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(CURRENT DATE,'YYMMDD')) AND (t1.TRQTY<>0)) AND t1.tcode IN ('IP','PQ','RM','SA','RP','RS','IS','IA','VR','IU','RC','SC','SM','SP','SS','LA')
GROUP BY  t1.ITNBR, t2.ITCLS, t1.HOUSE,
(CASE 
        WHEN t2.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t2.ITCLS IN ('PANL') THEN 'Panel'
        WHEN t2.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'
        WHEN t2.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t2.ITCLS LIKE 'T%' THEN 'RP'
		WHEN t2.ITCLS LIKE 'R%' THEN 'RP'
        WHEN t2.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t2.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t2.ITCLS LIKE 'Z%' AND t2.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t2.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t2.ITCLS IN ('BBFR','WVHC') THEN 'Verona'
        WHEN t2.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t2.ITCLS IN ('ZACM','ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC') THEN 'UPH'
        ELSE 'RawMaterial' END)