select t1.WCSCONTAINERNUMBER, t1.WCSORIGIN, t1.WCSDESTINATION, t1.WCSORDER, t1.WCSITEMNUMBER, t1.WCSSERIALNUMBER,t1.WCSADDEDTIMESTAMP,
t1.WCSADDEDUSER,t1.WCSADDEDPROGRAM, t1.WCSARCHIVETIMESTAMP, t3.B2Z95S as CUBES, t3.ITCLS,
(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t3.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t3.ITCLS IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
From ASHLEYARCL.WVCNTSDA t1, AFILELIBL.ITMEXT t2, AMFLIBL.ITMRVA t3
where t1.WCSADDEDTIMESTAMP between ? and ? and t1.WCSITEMNUMBER= t2.ITNBR and t1.WCSITEMNUMBER = t3.itnbr and t1.WCSORIGIN=t3.stid
order by  t1.WCSCONTAINERNUMBER 