-- Pull out SN scanned into temp ctn and real ctn, create by Jimshen on Oct.01.2021

SELECT * 
FROM
(
SELECT a.WCICONTAINERNUMBER AS CTN,a.WCIDESTINATION,a.WCIORDER,a.WCIITEMNUMBER,
a.WCIQUANTITYREQUIRED,a.WCIQUANTITYLOADED,a.WCILASTMAINTENANCETIMESTAMP,t3.ITCLS,t5.CUBES*a.WCIQUANTITYLOADED as Cubes,
	(CASE 
		WHEN a.WCICONTAINERNUMBER LIKE 'MRUN%' THEN 'InTempCTN'
		WHEN a.WCICONTAINERNUMBER LIKE 'KECR%' THEN 'InTempCTN'
		WHEN a.WCICONTAINERNUMBER LIKE 'KHO%' THEN 'InTempCTN'
		WHEN a.WCICONTAINERNUMBER LIKE 'M3K%' THEN 'InTempCTN'
		WHEN a.WCICONTAINERNUMBER LIKE 'M3E%' THEN 'InTempCTN'
		WHEN a.WCICONTAINERNUMBER LIKE 'M3H%' THEN 'InTempCTN'
		WHEN a.WCICONTAINERNUMBER LIKE 'RUN%' THEN 'InTempCTN'
		ELSE 'InRealCTN' END) AS "CTN_Status",
-- MIL PRODUCTS SEPERATED -- updated on Aug.28.2021
	(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t3.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t3.ITCLS IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'Check' END) AS Product
						
FROM LLUSAF.WVCNTID a, LLUSAF.WVCNTHD b,(SELECT DISTINCT t2.ITNBR,t2.ITCLS FROM AMFLIBL.ITEMBL t2 WHERE t2.HOUSE = '51' GROUP BY t2.ITNBR,t2.ITCLS) AS t3,
(SELECT DISTINCT t4.ITNBR,t4.CUBES FROM AFILELIBL.ITMEXT t4 GROUP BY t4.ITNBR,t4.CUBES) AS t5 
WHERE a.WCICONTAINERNUMBER = b.WCHCONTAINERNUMBER and b.WCHCONTAINERSTATUS 
NOT IN ('P','T') and a.WCIITEMNUMBER = t3.ITNBR and a.WCIITEMNUMBER=t5.ITNBR and t3.ITNBR = t5.ITNBR
) AS t1
WHERE t1."CTN_Status" NOT IN ('InRealCTN')