--MIL F/G SA Finished and Loading Scanned but still not SA containers, create by JimShen on Oct.08.2021 

(
SELECT t2.WCICONTAINERNUMBER,t2.WCIORIGIN,t2.WCIDESTINATION,t2.WCIORDER,t2.WCIITEMNUMBER,t2.WCIQUANTITYREQUIRED,t2.WCIQUANTITYLOADED,
t2.WCILASTMAINTENANCETIMESTAMP,t2.WCILASTMAINTENANCEUSER,t2.WCILASTMAINTENANCEPROGRAM,t1.WCHCONTAINERSTATUS,t1.WCHDOORNUMBER,t1.WCHDOCKID,
t1.WCHBUILDING,t1.WCHSEALNUMBER,t1.WCHCONTAINERSIZE,t1.WCHPOSTEDTIMESTAMP,t1.WCHLASTMAINTENANCETIMESTAMP,
t3.ITCLS,t5.CUBES*t2.WCIQUANTITYLOADED as Cubes, CEIL(t2.WCIQUANTITYLOADED/t5.ITMCQTY) AS Cartons, 
	(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t3.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t3.ITCLS IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'RP' END) AS Product,
	(CASE 
		WHEN t1.WCHCONTAINERSTATUS IN ('P','T') THEN 'SA_Done'
		WHEN t1.WCHCONTAINERSTATUS NOT IN ('P','T') THEN 'Loaded_But_Not_SA'
		ELSE 'PleaseCheck' END) AS CTN_Status,
DATE(t1.WCHPOSTEDTIMESTAMP) AS "Date",
(CASE 
	WHEN CHAR(TRIM(CHAR(HOUR(t1.WCHPOSTEDTIMESTAMP)))||TRIM(CHAR(MINUTE(t1.WCHPOSTEDTIMESTAMP)))||TRIM(CHAR(SECOND(t1.WCHPOSTEDTIMESTAMP))))
	BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END) AS SHIFT


FROM LLUSAF.WVCNTHD t1, LLUSAF.WVCNTID t2, (SELECT DISTINCT t2.ITNBR,t2.ITCLS FROM AMFLIBL.ITEMBL t2 WHERE t2.HOUSE = '51' GROUP BY t2.ITNBR,t2.ITCLS) AS t3,
(SELECT DISTINCT t4.ITNBR,t4.CUBES, t4.ITMCQTY FROM AFILELIBL.ITMEXT t4 GROUP BY t4.ITNBR,t4.CUBES,t4.ITMCQTY) AS t5 

WHERE t1.WCHCONTAINERNUMBER = t2.WCICONTAINERNUMBER AND t2.WCIITEMNUMBER = t3.ITNBR and t2.WCIITEMNUMBER=t5.ITNBR and t3.ITNBR = t5.ITNBR
and t1.WCHCONTAINERNUMBER not LIKE 'KECR%'
and t1.WCHCONTAINERNUMBER not LIKE 'M3K%'
and t1.WCHCONTAINERNUMBER not LIKE 'M3E%'
and t1.WCHCONTAINERNUMBER not LIKE 'M3H%'
and t1.WCHCONTAINERNUMBER not LIKE 'KHO%'
and t1.WCHCONTAINERNUMBER not LIKE 'MRUN%'
and t1.WCHCONTAINERNUMBER not LIKE 'RUN%' AND
((t1.WCHPOSTEDTIMESTAMP IS NULL) or (t1.WCHPOSTEDTIMESTAMP between char(current date - 30 days) and char(current date + 1 days)))
)
Union ALL

(SELECT t2.WCICONTAINERNUMBER,t2.WCIORIGIN,t2.WCIDESTINATION,t2.WCIORDER,t2.WCIITEMNUMBER,t2.WCIQUANTITYREQUIRED,t2.WCIQUANTITYLOADED,
t2.WCILASTMAINTENANCETIMESTAMP,t2.WCILASTMAINTENANCEUSER,t2.WCILASTMAINTENANCEPROGRAM,t1.WCHCONTAINERSTATUS,t1.WCHDOORNUMBER,t1.WCHDOCKID,
t1.WCHBUILDING,t1.WCHSEALNUMBER,t1.WCHCONTAINERSIZE,t1.WCHPOSTEDTIMESTAMP,t1.WCHLASTMAINTENANCETIMESTAMP,
t3.ITCLS,t5.CUBES*t2.WCIQUANTITYLOADED as Cubes,CEIL(t2.WCIQUANTITYLOADED/t5.ITMCQTY) AS Cartons, 
	(CASE 
        WHEN t3.ITCLS IN ('WPLS') THEN 'Plastics'
		WHEN t3.ITCLS IN ('PANL') THEN 'Panel'
		WHEN t3.ITCLS IN ('DECK','QA') THEN 'RawMaterial'
        WHEN t3.ITCLS IN ('WVBC','WVHC','WVCS') THEN 'Foundation'
        WHEN t3.ITCLS IN ('SLDK') THEN 'RP'
        WHEN t3.ITCLS LIKE 'T%' THEN 'RP'
        WHEN t3.ITCLS IN ('ZKIS') THEN 'Bedding'
		WHEN t3.ITCLS IN ('ZKIZ') THEN 'ZipperCover'
        WHEN t3.ITCLS LIKE 'Z%' AND t3.ITCLS LIKE '%K' THEN 'UnKits'
		WHEN t3.ITCLS IN ('PACS') THEN 'UnKits'
        WHEN t3.ITCLS IN ('BBFR') THEN 'Verona'
        WHEN t3.ITCLS IN ('ZDAA','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB') THEN 'CG'
        WHEN t3.ITCLS LIKE 'Z%' THEN 'UPH'
        ELSE 'RP' END) AS Product,
	(CASE 
		WHEN t1.WCHCONTAINERSTATUS IN ('P','T') THEN 'SA_Done'
		WHEN t1.WCHCONTAINERSTATUS NOT IN ('P','T') THEN 'Loaded_But_Not_SA'
		ELSE 'PleaseCheck' END) AS CTN_Status,
DATE(WCHPOSTEDTIMESTAMP) AS "Date",
(CASE 
	WHEN CHAR(TRIM(CHAR(HOUR(t1.WCHPOSTEDTIMESTAMP)))||TRIM(CHAR(MINUTE(t1.WCHPOSTEDTIMESTAMP)))||TRIM(CHAR(SECOND(t1.WCHPOSTEDTIMESTAMP))))
	BETWEEN '070000' AND '194459' THEN 'DS' ELSE 'NS' END) AS SHIFT

FROM ASHLEYARCL.WVCNTHDA t1, ASHLEYARCL.WVCNTIDA t2, (SELECT DISTINCT t2.ITNBR,t2.ITCLS FROM AMFLIBL.ITEMBL t2 WHERE t2.HOUSE = '51' GROUP BY t2.ITNBR,t2.ITCLS) AS t3,
(SELECT DISTINCT t4.ITNBR,t4.CUBES,t4.ITMCQTY FROM AFILELIBL.ITMEXT t4 GROUP BY t4.ITNBR,t4.CUBES,t4.ITMCQTY) AS t5 

WHERE t1.WCHCONTAINERNUMBER = t2.WCICONTAINERNUMBER AND t2.WCIITEMNUMBER = t3.ITNBR and t2.WCIITEMNUMBER=t5.ITNBR and t3.ITNBR = t5.ITNBR
and t1.WCHCONTAINERNUMBER not LIKE 'KECR%'
and t1.WCHCONTAINERNUMBER not LIKE 'M3K%'
and t1.WCHCONTAINERNUMBER not LIKE 'M3E%'
and t1.WCHCONTAINERNUMBER not LIKE 'M3H%'
and t1.WCHCONTAINERNUMBER not LIKE 'KHO%'
and t1.WCHCONTAINERNUMBER not LIKE 'MRUN%'
and t1.WCHCONTAINERNUMBER not LIKE 'RUN%' AND
(t1.WCHPOSTEDTIMESTAMP between char(current date - 30 days) and char(current date + 1 days))
)


