-- AFIPROD DISCO
Create view DISCO
as 
SELECT  T1.ITNBR, T1. MFPUS
FROM AFILELIB.ITMEXT T1
WHERE T1.MFPUS IN ('R','D') AND T1.



-- WVFHA DISCO
Create view AS_DISCO
as 
SELECT  T1.ITNBR, T1. MFPUS
FROM AFILELIBQ.ITMEXT T1
WHERE T1.MFPUS IN ('R','D')
