-- By PO to query which SN had already been shipped and details on customer

SELECT t2.AACOD1,t2.AAITM#,t2.AAEQP#,t2.AAADAT,t2.AAATIM,t2.AACOD2,t2.AAORD#,t2.AATRP#,CHAR(t2.AASER#) SN,t2.AAUCC#,t2.AACUS#,t2.AABOL#,t2.AAAUSR,
T2.AASER#||CHAR(to_date(T2.AAADAT||' '||right('000000'||ltrim(T2.AAATIM),6), 'yyyymmdd hh24:mi:ss')) as ShippedTime
FROM DISTLIBQ.ACTAUDT T2
WHERE T2.AACOD1 IN ('BT') AND T2.AAAPGM IN ('HJ321E') AND T2.AAITM# IN ('B5800-54W5')
AND t2.AASER#||CHAR(to_date(t2.AAADAT||' '||right('000000'||ltrim(t2.AAATIM),6), 'yyyymmdd hh24:mi:ss')) IN
-- SN|| max(DATE&TIME) AS STRING
(
SELECT t1.AASER#||CHAR(MAX(to_date(t1.AAADAT||' '||right('000000'||ltrim(t1.AAATIM),6), 'yyyymmdd hh24:mi:ss'))) AS ShippedTime
FROM  DISTLIBQ.ACTAUDT T1
WHERE T1.AACOD1 IN ('BT') AND T1.AAAPGM IN ('HJ321E') 
AND t1.AASER# IN 
(-- RECEIVED SN BY ITEM AND PO#
SELECT T1.AASER# SN FROM DISTLIBQ.ACTAUDT T1 WHERE T1.AAITM# IN ('B5800-54W5') AND T1.AACOD1 IN ('RC') AND t1.AATFR# IN ('PJ09Z53','PJ09T16') AND T1.AASCN# IN ('HJP151_232')
)
GROUP BY t1.AASER#
)

