-- Ashley SH RP Last Received Date 

SELECT a1.AAITM#,a1.LastReceivedDate,t3.ITCLS
FROM 
-- MAX RP into whse232 date
(SELECT t1.AAITM#, MAX(T1.AAADAT) AS LastReceivedDate
FROM DISTLIBQ.ACTAUDT T1
WHERE T1.AACOD1 IN ('RP','RC','MV') AND T1.AAAPGM LIKE 'HJ%' 
GROUP BY t1.AAITM#
) a1
LEFT JOIN 
-- ITEM NUMBER + ITEM CLASS
(SELECT  DISTINCT CHAR(TRIM(T2.ITNBR)) ITNBR, T2.ITCLS FROM AMFLIBQ.ITMRVA T2 WHERE T2.ITCLS NOT LIKE 'Z%' GROUP BY CHAR(TRIM(T2.ITNBR)),T2.ITCLS) T3 
ON a1.AAITM# = T3.ITNBR 
WHERE t3.ITCLS NOT LIKE 'Z%'