
SELECT AATWHS,AAITM#,SN,Received_Date
FROM 
(
SELECT a.AATWHS,a.AAITM#,CHAR(a.AASER#) SN, a.AAADAT Received_Date
FROM DISTLIBQ.ACTAUDT a
WHERE a.AACOD1 IN ('RC') AND a.AACOD2 IN ('SN') AND a.AATWHS IN ('232')
) T1
WHERE EXISTS
(SELECT 1 FROM 
(SELECT a.AAITM#,CHAR(a.AASER#) AASER#,MIN(a.AAADAT) AAADAT FROM DISTLIBQ.ACTAUDT a WHERE a.AASER#<>0 AND a.AATWHS IN ('232')
GROUP BY a.AAITM#,CHAR(a.AASER#)
) AS T2
WHERE T1.AATWHS = T2.AATWHS, T1.AAITM# = T2.AAITM# AND T1.SN = T2.AASER#)  
LIMIT 20







  