SELECT t1.TCODE, t1.ORDNO, t1.ITNBR, t2.ITCLS, t1.HOUSE, t1.UPDDT, t1.UPDTM, t1.TRQTY, t1.TRNDT, t1.LBHNO, t1.REFNO, t1.REASN, t1.USRSQ  
FROM AMFLIBQ.IMHIST t1, AMFLIBQ.ITMRVA t2, AMFLIBQ.t3 t3  
WHERE t2.ITNBR = t1.ITNBR AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND ((t1.HOUSE='232') AND 
(t1.UPDDT BETWEEN  '1210101' AND int('1'||substr(trim(char(CURRENT DATE)),3,2)||substr(trim(char(CURRENT DATE)),6,2)||substr(trim(char(CURRENT DATE)),9,2))) 
AND (t1.TRQTY<>0) AND t1.TCODE IN ('IA','SS','RC'))