-- Ashley SH open Trips

Select  t1.BDTRP#,t1.BDCUS#,t1.BDORD#,t1.BDITM#,t1.BDITMD,t1.BDINVN,t1.BDCTL#,t1.BDICLS,t1.BDCCLS,t1.BDITQT,t1.BDITCT,t1.BDITWT,t1.BDCTIM,t1.BDSHPNO,t2.BHTRP#,t2.BHWHS#,t2.BHTRPS,t2.BHPRVS,t2.BHCNTI,t2.BHCNTN,t2.BHSEL1,t2.BHLUSR,t2.BHLDAT,t2.BHLTIM,t2.BHLTYP,T2.BHRDAT, t2.BHRTIM,t2.BHZDAT,T2.BHZTIM,T2.BHTSNS,
(CASE 
    WHEN t1.BDICLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.BDITM#,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.BDITM#,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product
from DISTLIBQ.BTTRIPD t1 full join DISTLIBQ.BTTRIPH t2 on t1.BDTRP# = t2.BHTRP# 
where t2.BHWHS# IN ('232') and t2.BHLDAT between 20210101 and 29991231 and t2.BHTRPS in ('A','R','X')

order by t2.BHLDAT,t1.BDTRP#,t1.BDITM#


-- Ashley SH Open Orders
Select  t1.ORDNO,t3.CUSNM,t1.CCUSNO,t1.ITNBR,t1.COQTY,t1.QTYSH,t1.QTYBO,t2.TKNDAT,t2.RQSDAT,t1.MFIDT, t1.IAFLG,t2.SHPTO#, 
t1.ISLPR as "Selling Price", T4.CUSPO,t1.COQTY-t1.QTYSH-t1.QTYBO as OpenOrderQty,t5.ITCLS,
(CASE 
    WHEN t5.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product
from AFILELIBQ.CODATAN t1, AFILELIBQ.EXTORD t2,AFILELIBQ.ACUSMASJ t3, AFILELIBQ.COMAST t4, AMFLIBQ.ITMRVA t5
where
t2.XORDNO =t1.ORDNO AND t3.CUSNO = t1.CCUSNO and t1.ORDNO=t4.ORDNO and t1.ITNBR = T5.ITNBR and t1.house = T5.STID


-- INVENTORY PPT FOR BOB (open trips)
SELECT s1.PRODUCT,s1.BDITM#,sum(s1.BDITQT) as "Trip Demand"
FROM
(Select  t1.BDTRP#,t1.BDCUS#,t1.BDORD#,t1.BDITM#,t1.BDITMD,t1.BDINVN,t1.BDCTL#,t1.BDICLS,t1.BDCCLS,t1.BDITQT,t1.BDITCT,t1.BDITWT,t1.BDCTIM,
t1.BDSHPNO,t2.BHTRP#,t2.BHWHS#,t2.BHTRPS,t2.BHPRVS,t2.BHCNTI,t2.BHCNTN,t2.BHSEL1,t2.BHLUSR,t2.BHLDAT,t2.BHLTIM,t2.BHLTYP,T2.BHRDAT, t2.BHRTIM,
t2.BHZDAT,T2.BHZTIM,T2.BHTSNS,
(CASE 
    WHEN t1.BDICLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.BDITM#,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.BDITM#,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product
from DISTLIBQ.BTTRIPD t1 full join DISTLIBQ.BTTRIPH t2 on t1.BDTRP# = t2.BHTRP# 
where t2.BHWHS# IN ('232') and t2.BHLDAT between 20210101 and 29991231 and t2.BHTRPS in ('A','R','X')
order by t2.BHLDAT,t1.BDTRP#,t1.BDITM#) AS s1
Group by s1.PRODUCT,s1.BDITM#




-- INVENTORY PPT FOR BOB (open orders)

SELECT s2.product, s2.itnbr, sum(s2.OpenOrders) as "Open Orders"
FROM
(
Select  t1.ORDNO,t3.CUSNM,t1.CCUSNO,t1.ITNBR,t1.COQTY,t1.QTYSH,t1.QTYBO,t2.TKNDAT,t2.RQSDAT,t1.MFIDT, t1.IAFLG,t2.SHPTO#, 
t1.ISLPR as "Selling Price", T4.CUSPO,t1.COQTY-t1.QTYSH-t1.QTYBO as OpenOrders,t5.ITCLS,
(CASE 
    WHEN t5.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product


from AFILELIBQ.CODATAN t1, AFILELIBQ.EXTORD t2,AFILELIBQ.ACUSMASJ t3, AFILELIBQ.COMAST t4, AMFLIBQ.ITMRVA t5

where
t2.XORDNO =t1.ORDNO AND t3.CUSNO = t1.CCUSNO and t1.ORDNO=t4.ORDNO and t1.ITNBR = T5.ITNBR and t1.house = T5.STID
) as s2
group by s2.product, s2.itnbr



-- summary
SELECT z1.PRODUCT,z1.ITNBR,Sum(z1.Qty) as Qty,'OnHand' as "TYPE"
from 
(
SELECT t1.ITNBR,t1.ITCLS, SUM(t1.MOHTQ) as Qty,
(CASE 
    WHEN t1.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product
	
FROM AMFLIBQ.ITEMBL t1, AMFLIBQ.ITMRVA t2, AMFLIBQ.WHSMST t3
WHERE t2.ITCLS = t1.ITCLS AND t2.ITNBR = t1.ITNBR AND t1.HOUSE = t3.WHID 
AND t3.STID = t2.STID AND ((t1.MOHTQ<>0) 
AND (t1.HOUSE='232' Or t1.HOUSE='21'))
GROUP BY t1.ITNBR,t1.ITCLS
ORDER BY t1.ITNBR
)  as z1
group by z1.PRODUCT,z1.ITNBR

union all


-- 以下为open trip + open orders union
(SELECT s1.PRODUCT,s1.BDITM#,sum(s1.BDITQT) as "Trip Demand",'TripDemand' as Type
FROM
(Select  t1.BDTRP#,t1.BDCUS#,t1.BDORD#,t1.BDITM#,t1.BDITMD,t1.BDINVN,t1.BDCTL#,t1.BDICLS,t1.BDCCLS,t1.BDITQT,t1.BDITCT,t1.BDITWT,t1.BDCTIM,
t1.BDSHPNO,t2.BHTRP#,t2.BHWHS#,t2.BHTRPS,t2.BHPRVS,t2.BHCNTI,t2.BHCNTN,t2.BHSEL1,t2.BHLUSR,t2.BHLDAT,t2.BHLTIM,t2.BHLTYP,T2.BHRDAT, t2.BHRTIM,
t2.BHZDAT,T2.BHZTIM,T2.BHTSNS,
(CASE 
    WHEN t1.BDICLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.BDITM#,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.BDITM#,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product
from DISTLIBQ.BTTRIPD t1 full join DISTLIBQ.BTTRIPH t2 on t1.BDTRP# = t2.BHTRP# 
where t2.BHWHS# IN ('232') and t2.BHLDAT between 20210101 and 29991231 and t2.BHTRPS in ('A','R','X')
order by t2.BHLDAT,t1.BDTRP#,t1.BDITM#) as s1
Group by s1.PRODUCT,s1.BDITM#


UNION ALL 

SELECT s2.product, s2.itnbr, sum(s2.OpenOrders) as "Open Orders",'OpenOrders' as Type
FROM
(
Select  t1.ORDNO,t3.CUSNM,t1.CCUSNO,t1.ITNBR,t1.COQTY,t1.QTYSH,t1.QTYBO,t2.TKNDAT,t2.RQSDAT,t1.MFIDT, t1.IAFLG,t2.SHPTO#, 
t1.ISLPR as "Selling Price", T4.CUSPO,t1.COQTY-t1.QTYSH-t1.QTYBO as OpenOrders,t5.ITCLS,
(CASE 
    WHEN t5.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product

from AFILELIBQ.CODATAN t1, AFILELIBQ.EXTORD t2,AFILELIBQ.ACUSMASJ t3, AFILELIBQ.COMAST t4, AMFLIBQ.ITMRVA t5
where
t2.XORDNO =t1.ORDNO AND t3.CUSNO = t1.CCUSNO and t1.ORDNO=t4.ORDNO and t1.ITNBR = T5.ITNBR and t1.house = T5.STID
) as s2
group by s2.product, s2.itnbr)

