SELECT  
t1.AACOD1,t1.AACOD2,t1.AATWHS,t1.AAITM#,t1.AASER#,t1.AALIC#,t1.AATQTY,t1.AAEQP#,t1.AAADAT,
t1.AAATIM,t1.AAAUSR,t1.AAAPGM,t1.AAFARA,t1.AAFASL,t1.AAFSEC,t1.AAFTIR,t1.AATARA,
t1.AATASL,t1.AATSEC,t1.AATTIR,t1.AATFR#,t1.AATRP#,t1.AAORD#,t1.AAISQ#,t1.AAUCC#,
t1.AACUS#,t1.AAEBDG,t1.AASCN#,t1.AACREW

FROM DISTLIBQ.ACTAUDT t1
WHERE t1.AACOD1 in ('RC')




