SELECT t1.TCODE, t1.ORDNO, t1.ITNBR, t2.ITCLS, t1.HOUSE, t1.UPDDT, t1.UPDTM, t1.TRQTY, 
Date('20'||Substr(T1.UPDDT, 2, 2) || '-'||  Substr(T1.UPDDT, 4, 2)|| '-' ||substr(T1.UPDDT, 6, 2)) AS "DATE",
WEEK(DATE('20'||SUBSTR(CHAR(t1.UPDDT),2,2)||'-'||SUBSTR(CHAR(t1.UPDDT),4,2)||'-'||SUBSTR(CHAR(t1.UPDDT),6,2))) AS "WEEK",
YEAR(DATE('20'||SUBSTR(CHAR(t1.UPDDT),2,2)||'-'||SUBSTR(CHAR(t1.UPDDT),4,2)||'-'||SUBSTR(CHAR(t1.UPDDT),6,2))) AS "YEAR",
INTEGER(YEAR(DATE('20'||SUBSTR(CHAR(t1.UPDDT),2,2)||'-'||SUBSTR(CHAR(t1.UPDDT),4,2)||'-'||SUBSTR(CHAR(t1.UPDDT),6,2)))*100+WEEK(DATE('20'||SUBSTR(CHAR(t1.UPDDT),2,2)||'-'||SUBSTR(CHAR(t1.UPDDT),4,2)||'-'||SUBSTR(CHAR(t1.UPDDT),6,2)))) AS YearWeek,
(CASE 
        WHEN t2.ITCLS NOT LIKE 'Z%' THEN 'RP'
		WHEN t1.ITNBR LIKE '100-%' THEN 'CG'
		WHEN t1.ITNBR LIKE '5100-%' THEN 'CG'
		WHEN SUBSTR(t1.ITNBR,1,1) IN ('A','B','D','H','L','Q','R','T','W','Z') THEN 'CG'
		ELSE 'UPH' END) AS Product,
(CASE 
		WHEN t1.TCODE LIKE 'RP%' THEN 'Inbound'
		WHEN t1.TCODE LIKE 'SA%' THEN 'Outbound'
		ELSE 'CHECK' END) AS "IN/OUT"

FROM AMFLIBQ.IMHIST t1, AMFLIBQ.ITMRVA t2, AMFLIBQ.WHSMST t3  
WHERE t2.ITNBR = t1.ITNBR AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND (t1.HOUSE IN ('232') AND (t1.UPDDT>=? And t1.UPDDT<=?) AND (t1.TRQTY<>0)) and t1.TCODE IN ('RP','SA')








