SELECT t1.ITNBR, t1.HOUSE, t1.ITCLS, t1.MOHTQ, t1.WHSLC, t1.QTSYR, t2.ITDSC, t4.LLOCN, t4.LQNTY
FROM AMFLIBQ.ITEMBL t1, AMFLIBQ.ITMRVA t2, AMFLIBQ.WHSMST t3, AMFLIBQ.SLQNTY t4
WHERE t1.ITNBR = t4.ITNBR AND t4.ITNBR = t2.ITNBR AND t1.ITCLS= t2.ITCLS AND t1.HOUSE=t4.HOUSE AND t4.HOUSE = t3.WHID AND t3.STID = t2.STID AND ((t1.MOHTQ<>0) AND (t1.HOUSE='22'))
ORDER BY t1.ITNBR