
-- Version_03

SELECT ITNBR, ITDSC, ITCLS
FROM 
(
SELECT t2.ITNBR, t4.ITDSC, T2.ITCLS
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4,AMFLIBQ.WHSMST t3
WHERE T2.HOUSE=T3.WHID AND T3.STID=T4.STID AND T2.ITNBR=T4.ITNBR AND t2.HOUSE='232' AND t2.ITCLS NOT LIKE 'Z%'
) AS a WHERE NOT EXISTS (SELECT 1 FROM 
(
SELECT t2.ITNBR, t4.ITDSC, T2.ITCLS
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4,AMFLIBQ.WHSMST t3
WHERE T2.HOUSE=T3.WHID AND T3.STID=T4.STID AND T2.ITNBR=T4.ITNBR AND t2.HOUSE='PC1' AND t2.ITCLS NOT LIKE 'Z%'
) AS b 

WHERE a.ITNBR=b.ITNBR AND a.ITDSC=b.ITDSC AND a.ITCLS=b.ITCLS)




-- Version_02  WH232 NOT EXISTS PC1 RP ITEMS
SELECT *
FROM 
(
SELECT t4.ITNBR as ItemNumber, t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4
WHERE t2.ITNBR = t4.ITNBR AND t2.ITCLS = t4.ITCLS AND t2.HOUSE='232' AND t2.ITCLS NOT LIKE 'Z%'
) AS a
WHERE NOT EXISTS (SELECT 1 FROM 
(
SELECT t4.ITNBR as ItemNumber, t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4
WHERE t2.ITNBR = t4.ITNBR AND t2.ITCLS = t4.ITCLS AND t2.HOUSE='PC1' AND t2.ITCLS NOT LIKE 'Z%'
) AS b WHERE a.ItemNumber=b.ItemNumber AND a.ITNBR=b.ITNBR AND a.HOUSE=b.HOUSE AND a.MOHTQ=b.MOHTQ AND a.WHSLC=b.WHSLC AND a.ITCLS=b.ITCLS 
AND a.QTSYR=b.QTSYR AND a.B2Z95S=b.B2Z95S AND a.ITDSC=b.ITDSC)


SELECT *
FROM 
(
SELECT t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4,AMFLIBQ.WHSMST t3
WHERE T2.HOUSE=T3.WHID AND T3.STID=T4.STID AND T2.ITNBR=T4.ITNBR AND t2.HOUSE='232' AND t2.ITCLS NOT LIKE 'Z%'
) AS a WHERE NOT EXISTS (SELECT 1 FROM 
(
SELECT t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4,AMFLIBQ.WHSMST t3
WHERE T2.HOUSE=T3.WHID AND T3.STID=T4.STID AND T2.ITNBR=T4.ITNBR AND t2.HOUSE='PC1' AND t2.ITCLS NOT LIKE 'Z%'
) AS b 

WHERE a.ITNBR=b.ITNBR AND a.HOUSE=b.HOUSE AND a.MOHTQ=b.MOHTQ AND a.WHSLC=b.WHSLC AND a.ITCLS=b.ITCLS 
AND a.QTSYR=b.QTSYR AND a.B2Z95S=b.B2Z95S AND a.ITDSC=b.ITDSC)


--T1.HOUSE=T2.WHID AND T2.STID=T3.STID AND T1.ITNBR=T3.ITNBR


-- ITEM'S SAMPLE
SELECT t4.ITNBR, t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC, t1.TIHIUNLD, t1.PICKPUT, t1.ITMCLSID, t1.UNITSWIDE, t1.UNITLAYERS, t1.UNITSDEEP, 
t1.SCOOPQTY, t1.SKIDSIZE, t3.QTYCR, t3.NBSEAT, t3.CRTWIN, t3.CRTLIN, t3.CRTHIN, t3.PRDWIN, 
t3.PRDHIN, t3.PRDLIN, t3.ITMWEGHT

FROM AFILELIBQ.ITBEXT t1, AMFLIBQ.ITEMBL t2, AFILELIBQ.ITMEXT t3, AMFLIBQ.ITMRVA t4
WHERE t1.ITNBR = t4.ITNBR AND t2.HOUSE = t1.HOUSE AND t2.ITNBR = t1.ITNBR AND t2.ITNBR = t4.ITNBR 
AND t2.ITCLS = t4.ITCLS AND t3.ITNBR = t1.ITNBR AND t3.ITNBR = t2.ITNBR AND t3.ITNBR = t4.ITNBR 
AND t4.STID = t1.HOUSE AND ((t1.HOUSE='232')) AND t4.ITNBR LIKE 'A5%'

-- select * from B where not exists(select 1 from A where B.col1 = A.col1 and B.col2 = A.col2 and B.col3 = A.col3)
-- Version_01
SELECT *
FROM 
(
SELECT t4.ITNBR as ItemNumber, t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC, t1.PICKPUT, t1.ITMCLSID,t3.QTYCR
FROM AFILELIBQ.ITBEXT t1, AMFLIBQ.ITEMBL t2, AFILELIBQ.ITMEXT t3, AMFLIBQ.ITMRVA t4
WHERE t1.ITNBR = t4.ITNBR AND t2.HOUSE = t1.HOUSE AND t2.ITNBR = t1.ITNBR AND t2.ITNBR = t4.ITNBR 
AND t2.ITCLS = t4.ITCLS AND t3.ITNBR = t1.ITNBR AND t3.ITNBR = t2.ITNBR AND t3.ITNBR = t4.ITNBR 
AND t4.STID = t1.HOUSE AND ((t1.HOUSE='232')) AND t2.ITCLS NOT LIKE 'Z%'
) as a

WHERE not exists (select 1 from (
SELECT t4.ITNBR as ItemNumber, t2.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC, t1.PICKPUT, t1.ITMCLSID,t3.QTYCR
FROM AFILELIBQ.ITBEXT t1, AMFLIBQ.ITEMBL t2, AFILELIBQ.ITMEXT t3, AMFLIBQ.ITMRVA t4
WHERE t1.ITNBR = t4.ITNBR AND t2.HOUSE = t1.HOUSE AND t2.ITNBR = t1.ITNBR AND t2.ITNBR = t4.ITNBR 
AND t2.ITCLS = t4.ITCLS AND t3.ITNBR = t1.ITNBR AND t3.ITNBR = t2.ITNBR AND t3.ITNBR = t4.ITNBR 
AND t4.STID = t1.HOUSE AND ((t1.HOUSE='PC1')) AND t2.ITCLS NOT LIKE 'Z%'
) as b 
Where a.ItemNumber = b.ItemNumber and a.ITNBR = b.ITNBR AND a.HOUSE = b.HOUSE AND a.MOHTQ = b.MOHTQ AND a.WHSLC = b.WHSLC and a.ITCLS = b.ITCLS 
and a.QTSYR = b.QTSYR and a.B2Z95S = b.B2Z95S and a.ITDSC = b.ITDSC and a.PICKPUT = b.PICKPUT and a.ITMCLSID = b.ITMCLSID and a.QTYCR = b.QTYCR) 






