-- WH232 RP Item not exist in PC1, created by Jimshen on Oct.08.2021

SELECT ITNBR, ITDSC, ITCLS
FROM 
(
SELECT t2.ITNBR, t4.ITDSC, T2.ITCLS
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4,AMFLIBQ.WHSMST t3
WHERE T2.HOUSE=T3.WHID AND T3.STID=T4.STID AND T2.ITNBR=T4.ITNBR AND t2.HOUSE='232' AND t2.ITCLS NOT LIKE 'Z%'
) AS a 

WHERE NOT EXISTS 
(SELECT 1 FROM 
(
SELECT t2.ITNBR, t4.ITDSC, T2.ITCLS
FROM AMFLIBQ.ITEMBL t2, AMFLIBQ.ITMRVA t4,AMFLIBQ.WHSMST t3
WHERE T2.HOUSE=T3.WHID AND T3.STID=T4.STID AND T2.ITNBR=T4.ITNBR AND t2.HOUSE='PC1' AND t2.ITCLS NOT LIKE 'Z%'
) AS b 
WHERE a.ITNBR=b.ITNBR AND a.ITDSC=b.ITDSC AND a.ITCLS=b.ITCLS)