-- AshleySH OnHand+OpenPO+Received+Shipped+OpenCO, created by JimShen on May.16.2022

SELECT z1.Item#,z1.OnHand,z1.NextSixWksOPENPO AS "NextSixWksOpenPO",z1.PastSixWksShiped AS "PastSixWksShipped",z1.PastSixWksReceived as "PastSixWksReceived", z1.NextSixWksOpenCO as "NextSixWksOpenCO", z1.AfterSixWksOpenCO AS "AfterSixWksOpenCO",
-- Products seperated
(CASE 
    WHEN z2.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(z2.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(z2.ITNBR,1,5)='5100-' THEN 'CG'
	WHEN SUBSTR(z2.ITNBR,1,1) in ('B','D','E','H','P','T','W','Z','Y') THEN 'CG'
	WHEN SUBSTR(z2.ITNBR,1,1) in ('A','L','Q','R') THEN 'Accessory'
	ELSE 'UPH' END) as Product,
z2.B2Z95S*z1.OnHand as "OnHandCubes"
FROM
(
-- y1 full union y2 ---- OH+OPENPO+PAST 6W RECEIVED AND SHIPPED + OPENCO 
SELECT y1.OnHand,y1.NextSixWksOPENPO,y1.PastSixWksShiped,y1.PastSixWksReceived, y2.NextSixWksOpenCO, y2.AfterSixWksOpenCO,
(CASE 
	WHEN y2.ITNBR<>'' THEN y2.ITNBR
	ELSE y1.Item# END) as Item# 
FROM
(
-- x1 full join x2 -- OnHand + OpenPO + 6W_Received + 6W_Shipped    
SELECT x1.MOHTQ as OnHand,x1.NextSixWksOPENPO,x2.PastSixWksShiped,x2.PastSixWksReceived,
(CASE 
	WHEN x2.ITNBR<>'' THEN x2.ITNBR
	ELSE x1.Item# END) as Item# 
FROM
(
-- Ashley SH OnHand full join OPEN PO IN NEXT SIX WEEKS
SELECT s1.MOHTQ, s2.NextSixWksOPENPO, 
(CASE 
	WHEN s2.ITNBR<>'' THEN s2.ITNBR
	ELSE s1.ITNBR END) as Item# 
FROM 
--Ashley SH OnHand
(SELECT T1.ITNBR, SUM(T1.MOHTQ) AS MOHTQ, SUM(T1.QTSYR) AS QTSYR
FROM AMFLIBQ.ITEMBL T1,AMFLIBQ.WHSMST T3
WHERE T1.HOUSE = T3.WHID AND ((T1.MOHTQ<>0) AND T1.HOUSE IN ('232','21'))
GROUP BY T1.ITNBR, T1.HOUSE
ORDER BY T1.ITNBR
) as s1
FULL JOIN
-- OPEN PO IN NEXT SIX WEEKS
(SELECT c.ITNBR, SUM(c.QTYOR) AS NextSixWksOPENPO
FROM AFILELIBQ.ITBEXT a, AFILELIBQ.ITMEXT b, AMFLIBQ.POITEM c, AMFLIBQ.POMAST d, AMFLIBQ.VENNAML0 e
WHERE a.ITNBR = b.ITNBR AND c.ITNBR = b.ITNBR AND c.ORDNO = d.ORDNO AND 
d.VNDNR = e.VNDRVM AND c.HOUSE = a.HOUSE AND d.HOUSE = c.HOUSE
AND d.HOUSE='232' AND d.PSTTS IN ('10','20','30') and c.DUEDT  
BETWEEN  int('1'||substr(trim(char(CURRENT DATE - 30 days)),3,2)||substr(trim(char(CURRENT DATE- 30 days)),6,2)||substr(trim(char(CURRENT DATE- 30 days)),9,2)) 
AND int('1'||substr(trim(char(CURRENT DATE + 43 days)),3,2)||substr(trim(char(CURRENT DATE + 43 days)),6,2)||substr(trim(char(CURRENT DATE + 43 days)),9,2))
GROUP BY C.ITNBR 
ORDER BY c.ITNBR) as s2
on s1.ITNBR = s2.ITNBR
) x1

FULL JOIN
--Received and Shipped in past six weeks
(SELECT T1.ITNBR,
SUM(CASE WHEN T1.TCODE IN ('SA') THEN T1.TRQTY ELSE 0 END) AS PastSixWksShiped,
SUM(CASE WHEN T1.TCODE IN ('RP') THEN T1.TRQTY ELSE 0 END) AS PastSixWksReceived
FROM AMFLIBQ.IMHIST T1, AMFLIBQ.WHSMST T3
WHERE T1.HOUSE = T3.WHID AND T1.HOUSE IN ('232','21') 
AND T1.UPDDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 43 Days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
AND T1.TRQTY<>0 AND T1.TCODE in ('SA','RP') 
GROUP BY T1.ITNBR
ORDER BY T1.ITNBR 
) x2
ON x1.Item#=x2.ITNBR
) y1

FULL JOIN
(
--OPEN CO(INCLUDE TRIPS)
SELECT T2.ITNBR,
SUM(CASE 
		WHEN (YEAR(CURRENT DATE)*100+WEEK(DATE(SUBSTR(CHAR(T2.MFIDT),1,4)||'-'||SUBSTR(CHAR(T2.MFIDT),5,2)||'-'||SUBSTR(CHAR(T2.MFIDT),7,2))))-(YEAR(CURRENT DATE)*100+WEEK(CURRENT DATE))<=6 THEN T2.COQTY-T2.QTYSH ELSE 0 END) AS NextSixWksOpenCO,
SUM(
	CASE 
		WHEN (YEAR(CURRENT DATE)*100+WEEK(DATE(SUBSTR(CHAR(T2.MFIDT),1,4)||'-'||SUBSTR(CHAR(T2.MFIDT),5,2)||'-'||SUBSTR(CHAR(T2.MFIDT),7,2))))-(YEAR(CURRENT DATE)*100+WEEK(CURRENT DATE))>6 THEN T2.COQTY-T2.QTYSH ELSE 0 END) AS AfterSixWksOpenCO
FROM AFILELIBQ.ACUSMASJ T1, AFILELIBQ.CODATAN T2, AFILELIBQ.COMAST T3, AFILELIBQ.EXTORD T4
WHERE T3.ORDNO = T2.ORDNO AND T2.ORDNO = T4.XORDNO AND T4.CUSTNO = T1.CUSNO
GROUP BY T2.ITNBR
ORDER BY T2.ITNBR 
) y2
ON y1.Item# = y2.ITNBR
) z1

LEFT JOIN 
(SELECT T1.ITNBR,T1.ITCLS,T1.B2Z95S
FROM AMFLIBQ.ITMRVA T1
GROUP BY T1.ITNBR,T1.ITCLS,T1.B2Z95S
) AS z2
ON z1.Item#=z2.ITNBR
WHERE z2.ITCLS LIKE 'Z%'