-- WH Trx Summary in qty and amount  DSN=AFIBI
SELECT X.ITNBR, X.HOUSE, X.ITCLS,X.DATE,X.WEEK,X.YEAR,X.YEAR*100+X.WEEK AS "YearWeek",X.TRQTY,Y.PAMNT "UP($USD)",
(CASE 
    WHEN X.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(X.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(X.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
(CASE 
		WHEN X.TCODE IN ('RP') THEN 'IN'
		WHEN X.TCODE IN ('SA') THEN 'OUT'
		ELSE 'CHECK' END ) as "TYPE",
(CASE 
    WHEN Y.PAMNT IS NULL AND X.ITCLS NOT LIKE 'Z%' THEN 0
	WHEN Y.PAMNT IS NULL AND X.ITCLS LIKE 'Z%' THEN X.TRQTY*50
	ELSE X.TRQTY*Y.PAMNT END) as "AMT($USD)"	
FROM
(
SELECT T1.TCODE, T1.ITNBR, T1.HOUSE, T2.ITCLS,T1.TRQTY,
DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2)) AS DATE,              
WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS WEEK,
YEAR(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS YEAR
FROM AMFLIBA.IMHIST T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3
WHERE T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND T1.HOUSE='335' 
AND T1.UPDDT BETWEEN '1210101' AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
AND T1.TRQTY<>0 AND T1.TCODE IN ('RP','SA') 
ORDER BY T1.ITNBR 
) AS X 
LEFT JOIN (SELECT PRICE.PITEM, PRICE.PAMNT FROM AFILELIB.PRICE PRICE WHERE PRICE.PRICCD='FOBARC' ORDER BY PRICE.PITEM) as Y 
ON X.ITNBR = Y.PITEM