SELECT X.CUSNO, X.CUSNM, X.ENTDAT, X.RPKEY, X.MODEL, X.SHPDAT, X.ORDPCK, X.TRIP#, X.WHOSE, X.SHPCTY, 
X.ITEMNO, X.ITDSC, X.QTY, X.SHPFLG, X.PCKDTE, X.PCKTME, Y.SN, Y.LOCATION
FROM
-- Ashton RP Open Order
(SELECT ARPHEDR.CUSNO, CUSMAS.CUSNM, ARPHEDR.ENTDAT, CHAR(ARPHEDR.RPKEY) RPKEY, ARPHEDR.MODEL, ARPHEDR.SHPDAT, ARPHEDR.ORDPCK, ARPHEDR.TRIP#, ARPHEDR.WHOSE, ARPHEDR.SHPCTY, ARPDETL.ITEMNO, ITMRVA.ITDSC, ARPDETL.QTY, ARPDETL.SHPFLG, ARPDETL.PCKDTE, ARPDETL.PCKTME
FROM D20ACF9V.AFILELIB.ARPDETL ARPDETL, D20ACF9V.AFILELIB.ARPHEDR ARPHEDR, D20ACF9V.AMFLIBA.CUSMAS CUSMAS, D20ACF9V.AMFLIBA.ITMRVA ITMRVA
WHERE ARPHEDR.RPKEY = ARPDETL.RPKEY AND ARPHEDR.CUSNO = CUSMAS.CUSNO AND ARPDETL.ITEMNO = ITMRVA.ITNBR AND ARPHEDR.WHOSE = ITMRVA.STID AND ((ARPHEDR.ACTCOD='A') AND (ARPHEDR.ENTDAT Between ? And ?) AND (ARPHEDR.WHOSE='335') AND (ARPHEDR.SHPDAT=0))
ORDER BY ARPHEDR.ENTDAT, ARPHEDR.RPKEY) AS X

LEFT JOIN
-- MAKING OPTION 1380 SN STRING + RP042xxx STRING
(SELECT T1.TDITEM, T1.TDAPO#, replace(replace(xml2clob(xmlagg(xmlelement(NAME a, T1.TDTAG#||','))),'<A>',''),'</A>','') AS SN,
replace(replace(xml2clob(xmlagg(xmlelement(NAME a, (CASE
	WHEN LENGTH(TRIM(TDASLE))=2 THEN TDAREA||'0'||TDASLE||TDSEC||TDTIER
	WHEN LENGTH(TRIM(TDASLE))=3 THEN TDAREA||TDASLE||TDSEC||TDTIER
	ELSE '' END)||','))),'<A>',''),'</A>','') AS LOCATION

FROM DISTLIB.TAGINVD2 T1
WHERE T1.TDITEM = 'RP ORDER' AND T1.TDMDAT BETWEEN '1220101' AND '1231231'

GROUP BY T1.TDITEM, T1.TDAPO#) AS Y

ON X.RPKEY = Y.TDAPO#




----------------------------------------------------------------------------------------
SELECT CONCAT(T1.TDTAG#,'') as SN,T1.TDSKU#,TDITEM,TDREC#,TDAPO#,TDREG#,TDWHSE,
(CASE
	WHEN LENGTH(TRIM(TDASLE))=2 THEN TDAREA||'0'||TDASLE||TDSEC||TDTIER
	WHEN LENGTH(TRIM(TDASLE))=3 THEN TDAREA||TDASLE||TDSEC||TDTIER
	ELSE '' END) AS LOCATION,
TDMDAT,TDMTME,TDMUSR,TDMPGM,TDVDAT
FROM DISTLIB.TAGINVD2 T1
WHERE T1.TDITEM = 'RP ORDER' AND (T1.TDMDAT>=? AND T1.TDMDAT<= ?) AND TDWHSE = '335'
Order by T1.TDMDAT