
-- MIL EOL SCANNED M% SN
SELECT T1.AAAPGM,T1.AACOD1,T1.AACOD2,T1.AAORD#,T1.AAITM#,CHAR(T1.AASER#) AS SN,T1.AATQTY,T1.AAADAT,T1.AAATIM,T1.AATWHS
FROM DISTLIBL.ACTAUDT T1
WHERE T1.AATWHS IN ('51') AND T1.AATARA = 'UC' AND T1.AAITM# LIKE 'M%' AND 
T1.AAADAT BETWEEN '20180101' AND '20291231'


-- ASHTON PO RECEIVED SN
SELECT W.SN,W.AAITM#,W.AAEQP#,W.AAADAT,W.AAATIM,W.AATWHS,W.AATFR#
FROM (
-- table W include current SN received and archived SN received of M%
(SELECT DISTINCT CHAR(T2.AASER#) AS SN,T2.AAITM#,T2.AAEQP#,T2.AAADAT,T2.AAATIM,T2.AATWHS,T2.AATFR#
FROM DISTLIB.ACTAUDT T2
WHERE T2.AAAPGM IN ('HJPOTOWA') AND T2.AACOD1 IN ('RC') AND T2.AACOD2 IN ('SN') AND T2.AATWHS IN ('335')
AND T2.AATARA IN ('AC') AND T2.AAITM# LIKE 'M%' AND T2.AAADAT BETWEEN '20190601' AND '20291231')
UNION ALL
(SELECT DISTINCT CHAR(T2.AASER#) AS SN,T2.AAITM#,T2.AAEQP#,T2.AAADAT,T2.AAATIM,T2.AATWHS,T2.AATFR#
FROM DISTLIBH.ACTAUDT T2
WHERE T2.AAAPGM IN ('HJPOTOWA') AND T2.AACOD1 IN ('RC') AND T2.AACOD2 IN ('SN') AND T2.AATWHS IN ('335')
AND T2.AATARA IN ('AC') AND T2.AAITM# LIKE 'M%' AND T2.AAADAT BETWEEN '20190601' AND '20291231')
) AS W
WHERE NOT EXISTS
	-- Remove BT transactons that be picked SN 
	 (SELECT 1
	  FROM (
	      SELECT T8.SN
		  FROM (
		  (SELECT CHAR(a.AASER#) AS SN
		  FROM DISTLIB.ACTAUDT a
		  WHERE a.AAAPGM IN ('HJ321E') AND a.AACOD1 IN ('BT') AND a.AACOD2 IN ('SN') AND a.AACOD3 IN ('HJ') AND a.AAFWHS IN ('335')
		  AND a.AAITM# LIKE 'M%' AND a.AAADAT BETWEEN '20190101' AND '20291231')
		  UNION ALL
		  (SELECT CHAR(a.AASER#) AS SN
		  FROM DISTLIBH.ACTAUDT a
		  WHERE a.AAAPGM IN ('HJ321E') AND a.AACOD1 IN ('BT') AND a.AACOD2 IN ('SN') AND a.AACOD3 IN ('HJ') AND a.AAFWHS IN ('335')
		  AND a.AAITM# LIKE 'M%' AND a.AAADAT BETWEEN '20190101' AND '20291231')) T8
/*		  WHERE NOT EXISTS
	       -- removed unloaded SN
						(SELECT 1
						FROM (						
						(SELECT CHAR(d.AASER#) AS SN
								FROM DISTLIB.ACTAUDT d
								WHERE d.AAAPGM IN ('HJ321E') AND d.AACOD1 IN ('BT') AND d.AACOD2 IN ('SN') AND d.AACOD3 IN ('UL') 
								AND d.AATWHS IN ('335') AND d.AAITM# LIKE 'M%' AND d.AAADAT BETWEEN '20190101' AND '20291231'
								)
								UNION ALL
								(SELECT CHAR(d.AASER#) AS SN
								FROM DISTLIBH.ACTAUDT d
								WHERE d.AAAPGM IN ('HJ321E') AND d.AACOD1 IN ('BT') AND d.AACOD2 IN ('SN') AND d.AACOD3 IN ('UL') 
								AND d.AATWHS IN ('335') AND d.AAITM# LIKE 'M%' AND d.AAADAT BETWEEN '20190101' AND '20291231'
								)) AS zz
						 WHERE T8.SN=zz.SN)
*/						 
		  ) T9
	 WHERE W.SN=T9.SN)
		  
		  