-- Ashton M% shipped trips for Kim by Jimshen on Apr.14.2022

(SELECT T1.AACOD1,T1.AAFWHS, T1.AASCN#,T1.AAAUSR,T1.AATRP#, T1.AAORD#,T1.AAITM#,T1.AAUCC#,T1.AATQTY,T1.AACUS#,T1.AABOL#,
T1.AAEQP#,T1.AAADAT,T1.AAATIM,T1.AASER#
FROM DISTLIB.ACTAUDT T1
WHERE T1.AACOD1 IN ('BT') AND T1.AAFWHS IN ('335') AND T1.AAITM# LIKE 'M%' AND T1.AAADAT BETWEEN ? AND ?
)
UNION ALL
(SELECT T1.AACOD1,T1.AAFWHS, T1.AASCN#,T1.AAAUSR,T1.AATRP#, T1.AAORD#,T1.AAITM#,T1.AAUCC#,T1.AATQTY,T1.AACUS#,T1.AABOL#,
T1.AAEQP#,T1.AAADAT,T1.AAATIM,T1.AASER#
FROM DISTLIBH.ACTAUDT T1
WHERE T1.AACOD1 IN ('BT') AND T1.AAFWHS IN ('335') AND T1.AAITM# LIKE 'M%' AND T1.AAADAT BETWEEN ? AND ?
)
limit 10
