select  a.ITNBR, a.HOUSE, a.ITCLS, a.MOHTQ, a.WHSLC, a.QTSYR, a.ITDSC, a.MFPUS,a.DOFLS,a.QTSMO,a.BEGIN,
a.RECMO,a.OPEN_PO,a.LDQOH,b.PAMNT "UnitPrice($USD)",b.PAMNT*a.MOHTQ "AMT($USD)"
from
(
SELECT T1.ITNBR,T4.PAMNT "UnitPrice($USD)",T1.ITDSC,T1.VNDNR, T1.WEGHT,T1.B2COCD,T3.VNNMVM,T3.VNMAVM,T1.B2Z95S as cubes,
T1.ITCLS, T2.MFPUS,T2.QTYCR,T2.SERCOLNUM,T2.SERIES,T2.CRTLIN,T2.CRTWIN,T2.CRTHIN,T2.PRDLIN,T2.PRDWIN,T2.PRDHIN 
FROM AMFLIBA.ITMRVA T1 LEFT JOIN AFILELIB.ITMEXT T2 ON T1.ITNBR=T2.ITNBR 
LEFT JOIN AMFLIBA.VENNAMV0 T3 ON T1.VNDNR=T3.VNDRVM
LEFT JOIN (SELECT * FROM AFILELIB.PRICE p WHERE p.PRICCD in ('FOBARC')) AS T4  ON T1.ITNBR=T4.PITEM 
WHERE T1.STID='335'

) as a

left join  

(SELECT *
FROM AFILELIB.PRICE a
WHERE a.PRICCD in ('FOBARC')) b on a.itnbr=b.pitem