
--ASHTON OPEN ORDRE VS TRIPS

-- Open Orders Detail
Select  t1.ORDNO,t3.CUSNM,t1.CCUSNO,t1.ITNBR,t1.COQTY,t1.QTYSH,t1.QTYBO,t2.TKNDAT,t2.RQSDAT,t1.MFIDT, t1.IAFLG,t2.SHPTO#, 
t1.ISLPR as "Selling Price", T4.CUSPO,t1.COQTY-t1.QTYSH-t1.QTYBO as OpenOrders,t5.ITCLS,
(CASE 
    WHEN t5.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','M','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product
from AFILELIB.CODATAN t1, AFILELIB.EXTORD t2,AFILELIB.ACUSMASJ t3, AFILELIB.COMAST t4, AMFLIBA.ITMRVA t5
where
t2.XORDNO =t1.ORDNO AND t3.CUSNO = t1.CCUSNO and t1.ORDNO=t4.ORDNO and t1.ITNBR = T5.ITNBR and t1.house = T5.STID and t1.house in ('335')



-- trip demand
Select  t1.BDTRP#,t1.BDCUS#,t1.BDORD#,t1.BDITM#,t1.BDITMD,t1.BDINVN,t1.BDCTL#,t1.BDICLS,t1.BDCCLS,t1.BDITQT,t1.BDITCT,t1.BDITWT,t1.BDCTIM,
t2.BHTRP#,t2.BHWHS#,t2.BHTRPS,t2.BHPRVS,t2.BHCNTI,t2.BHCNTN,t2.BHSEL1,t2.BHLUSR,t2.BHLDAT,t2.BHLTIM,t2.BHLTYP,T2.BHRDAT, t2.BHRTIM,
t2.BHZDAT,T2.BHZTIM,T2.BHTSNS,
(CASE 
    WHEN t1.BDICLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.BDITM#,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.BDITM#,1,1) in ('A','B','D','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product

from DISTLIB.BTTRIPD t1 full join DISTLIB.BTTRIPH t2 on t1.BDTRP# = t2.BHTRP# 

where t2.BHWHS# IN ('335') and t2.BHLDAT between 20210101 and 29991231 and t2.BHTRPS in ('A','R','X')

order by t2.BHLDAT,t1.BDTRP#,t1.BDITM#
