-- BI Ashton Discontinued query, created on Nov.26 and referred on RK_ONHAND

SELECT  a.ITNBR, a.HOUSE, a.ITCLS, a.MOHTQ, a.WHSLC, a.QTSYR, a.ITDSC, a.MFPUS,a.DOFLS,a.QTSMO,a.BEGIN,
a.RECMO,a.OPEN_PO,a.LDQOH,b.PAMNT "UnitPrice($USD)",b.PAMNT*a.MOHTQ "AMT($USD)",
(CASE 
    WHEN a.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(a.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(a.ITNBR,1,1)='M' THEN 'MATTRESS'	
	WHEN SUBSTR(a.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
b2.OPEN_CO,b2.Trip_Qty

FROM
(
SELECT T1.ITNBR, T1.HOUSE, T1.ITCLS, T1.MOHTQ, T1.WHSLC, T1.QTSYR, T2.ITDSC, T4.MFPUS,T1.DOFLS,T1.QTSMO,T1.BEGIN,T1.RECMO,T1.MPUPQ OPEN_PO,T1.LDQOH
FROM AMFLIBA.ITEMBL T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3, AFILELIB.ITMEXT T4
WHERE T2.ITCLS = T1.ITCLS AND T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND T1.HOUSE='335' and T1.ITNBR = t4.itnbr AND T1.MOHTQ<>0 AND T1.ITNBR NOT LIKE 'M%'
 ) AS a

LEFT JOIN  
(SELECT *
FROM AFILELIB.PRICE a
WHERE a.PRICCD in ('FOBARC')) b on a.itnbr=b.pitem

LEFT JOIN 
(--ASHTON OPEN ORDRE VS TRIPS
-- Open Orders Detail
SELECT  y1.ITNBR, sum(y1.OPEN_CO) OPEN_CO, sum(y1.Trip_Qty) Trip_Qty
FROM 
(
SELECT a1.ORDNO,a1.CUSNM,a1.CCUSNO,a1.ITNBR,a1.COQTY,a1.QTYSH,a1.QTYBO,(a1.COQTY-a1.QTYSH) OPEN_CO, a1.ITCLS,
a1.Product,x1.BDTRP#,x1.BDITQT as Trip_Qty
FROM 
(
Select  t1.ORDNO,t3.CUSNM,t1.CCUSNO,t1.ITNBR,t5.ITCLS,
(CASE 
    WHEN t5.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','M','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
 SUM(t1.COQTY) COQTY,SUM(t1.QTYSH) QTYSH,SUM(t1.QTYBO) QTYBO

from AFILELIB.CODATAN t1, AFILELIB.EXTORD t2,AFILELIB.ACUSMASJ t3, AFILELIB.COMAST t4, AMFLIBA.ITMRVA t5
where t2.XORDNO =t1.ORDNO AND t3.CUSNO = t1.CCUSNO and t1.ORDNO=t4.ORDNO and t1.ITNBR = T5.ITNBR and t1.house = T5.STID and t1.house in ('335')
AND t1.COQTY-t1.QTYSH<>0 and t4.MPROR NOT IN ('F','L','C')

GROUP BY t1.ORDNO,t3.CUSNM,t1.CCUSNO,t1.ITNBR,t5.ITCLS,
(CASE 
    WHEN t5.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','H','L','M','P','Q','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END)

) as a1

LEFT JOIN 
(-- trip demand
Select  t1.BDTRP#,t1.BDCUS#,t1.BDORD#,t1.BDITM#,SUM(t1.BDITQT) BDITQT
from DISTLIB.BTTRIPD t1 full join DISTLIB.BTTRIPH t2 on t1.BDTRP# = t2.BHTRP# 
where t2.BHWHS# IN ('335') and t2.BHLDAT between 20210101 and 29991231 and t2.BHTRPS in ('A','R','X')
GROUP BY t1.BDTRP#,t1.BDCUS#,t1.BDORD#,t1.BDITM#
order by t1.BDTRP#,t1.BDITM#
) x1  on a1.ORDNO||a1.ITNBR = x1.BDORD#||x1.BDITM#
) y1
GROUP BY y1.ITNBR
ORDER BY y1.ITNBR
)  b2 on a.itnbr = b2.ITNBR