SELECT t3.ITNBR, t3.QTYOR, t4.HOUSE, t4.ORDNO, t4.VNDNR, t4.PSTTS, t3.STKQT, t3.STKDT, 
t3.DYLDE, t3.DYLDL, t2.UUCCIM, t3.DUEDT, t1.ITMCLSID, t1.PICKPUT, t1.SCOOPQTY, t1.SKIDSIZE, 
t3.DOKDT, t3.MSNDD, t3.MSNSD, t5.VNNMVM, t3.QTYOR, t3.QTDEV, t3.STKQT,t6.ITCLS
FROM AFILELIB.ITBEXT t1, AFILELIB.ITMEXT t2, AMFLIBA.POITEM t3, AMFLIBA.POMAST t4, AMFLIBA.VENNAML0 t5,AMFLIBA.ITEMBL t6 

WHERE t1.ITNBR = t2.ITNBR AND t3.ITNBR = t2.ITNBR AND t2.ITNBR=t6.ITNBR AND t3.ORDNO = t4.ORDNO 
AND t4.VNDNR = t5.VNDRVM AND t3.HOUSE = t1.HOUSE AND t4.HOUSE = t3.HOUSE AND t3.HOUSE = t6.HOUSE 
AND t4.PSTTS IN ('30') AND t3.HOUSE='335'
ORDER BY t3.ITNBR, t3.DUEDT

