-- Ashton Container Utilization Summary 

SELECT x1.INIVDT, x1.INWHSE, x1.XCUS#, x1.ITCSNO, CHAR(x1.XNTRPN) AS TRIP#, x1.CountryCode, x1.CUSNM, SUM(x1.ITSHQT) AS SHIPPEDQTY,SUM(x1.CUBES) Cubes
FROM
(
(SELECT t4.INIVDT, t6.ITITNO, t4.INWHSE, t6.ITITCL, t6.ITSHQT, t2.UUCCIM, t7.XCUS#, t6.ITWHSE, t6.ITCSNO, t6.ITSPNO, T5.XNTRPN, T5.XNINVR, T5.XNORNO, 
t1.STACD, t2.CUBES, t4.INPONO, t1.CUSNM, t7.XFRGHT, t7.XTCONF, t7.XDSCNT, t6.ITPRIC,t1.CCTYN as CountryCode

FROM AFILELIB.ACUSMASJ t1, AFILELIB.ITMEXT t2, AMFLIBA.MBBZRES1 t3, AFILELIB.TSININA1 t4, AFILELIB.TSINXN t5, AFILELIB.TSITIN t6, AFILELIB.TSITXN t7
WHERE t4.INORNO = t7.XTORNO AND t7.XTORNO = t6.ITORNO AND t6.ITORNO = T5.XNORNO AND t4.ININVR = t7.XTINVR 
AND t7.XTINVR = t6.ITINVR AND t7.XTITNO = t6.ITITNO AND t6.ITCSNO = t1.CUSNO AND t6.ITITNO = t3.BZAITX 
AND t3.BZAITX = t2.ITNBR AND t4.INWHSE = t6.ITWHSE AND t6.ITINVR = T5.XNINVR AND t6.ITCSNO = t7.XCUS# 
AND t7.XCUS# = t4.INCSNO AND t7.XTITSQ = t6.ITITSQ AND t4.INRIDT = t7.XRIDAT AND t7.XRIDAT = t6.ITRIDT
AND ((t4.INWHSE='335') 
AND (t4.INIVDT>= 20210101
And t4.INIVDT<= int(substr(trim(char(CURRENT DATE)),1,4)||substr(trim(char(CURRENT DATE)),6,2)||substr(trim(char(CURRENT DATE)),9,2))) AND (t6.ITSHQT>0))
ORDER BY t4.INIVDT,T5.XNTRPN)
) x1
GROUP BY x1.INIVDT, x1.INWHSE, x1.XCUS#, x1.ITCSNO, CHAR(x1.XNTRPN), x1.CountryCode, x1.CUSNM
ORDER BY x1.INIVDT



-- Ashton Container Utilization by Month

SELECT x1.INIVDT, x1.INWHSE, CHAR(x1.XNTRPN) AS TRIP#, x1.CUSNM,SUM(x1.ITSHQT) AS SHIPPEDQTY,SUM(x1.CUBES*x1.ITSHQT) Cubes
FROM
(
(SELECT t4.INIVDT, t6.ITITNO, t4.INWHSE, t6.ITITCL, t6.ITSHQT, t2.UUCCIM, t7.XCUS#, t6.ITWHSE, t6.ITCSNO, t6.ITSPNO, T5.XNTRPN, T5.XNINVR, T5.XNORNO, 
t1.STACD, t2.CUBES, t4.INPONO, t1.CUSNM, t7.XFRGHT, t7.XTCONF, t7.XDSCNT, t6.ITPRIC,t1.CCTYN as CountryCode

FROM AFILELIB.ACUSMASJ t1, AFILELIB.ITMEXT t2, AMFLIBA.MBBZRES1 t3, AFILELIB.TSININA1 t4, AFILELIB.TSINXN t5, AFILELIB.TSITIN t6, AFILELIB.TSITXN t7
WHERE t4.INORNO = t7.XTORNO AND t7.XTORNO = t6.ITORNO AND t6.ITORNO = T5.XNORNO AND t4.ININVR = t7.XTINVR 
AND t7.XTINVR = t6.ITINVR AND t7.XTITNO = t6.ITITNO AND t6.ITCSNO = t1.CUSNO AND t6.ITITNO = t3.BZAITX 
AND t3.BZAITX = t2.ITNBR AND t4.INWHSE = t6.ITWHSE AND t6.ITINVR = T5.XNINVR AND t6.ITCSNO = t7.XCUS# 
AND t7.XCUS# = t4.INCSNO AND t7.XTITSQ = t6.ITITSQ AND t4.INRIDT = t7.XRIDAT AND t7.XRIDAT = t6.ITRIDT
AND ((t4.INWHSE='335') 
AND (t4.INIVDT>= 20210101
And t4.INIVDT<= int(substr(trim(char(CURRENT DATE)),1,4)||substr(trim(char(CURRENT DATE)),6,2)||substr(trim(char(CURRENT DATE)),9,2))) AND (t6.ITSHQT>0))
ORDER BY t4.INIVDT)
) x1
GROUP BY x1.INIVDT, x1.INWHSE, x1.XCUS#, x1.ITCSNO, CHAR(x1.XNTRPN), x1.CountryCode, x1.CUSNM
ORDER BY x1.INIVDT
LIMIT 200000000



-- Ashton shipped details

SELECT t4.INIVDT, t6.ITITNO, t4.INWHSE, t6.ITITCL, t6.ITSHQT, t2.UUCCIM, t7.XCUS#, t6.ITWHSE, t6.ITCSNO, t6.ITSPNO, CHAR(T5.XNTRPN) TRIP#, T5.XNINVR, T5.XNORNO, 
t1.STACD, t2.CUBES, t4.INPONO, t1.CUSNM, t7.XFRGHT, t7.XTCONF, t7.XDSCNT, t6.ITPRIC,t1.CCTYN as CountryCode

FROM AFILELIB.ACUSMASJ t1, AFILELIB.ITMEXT t2, AMFLIBA.MBBZRES1 t3, AFILELIB.TSININA1 t4, AFILELIB.TSINXN t5, AFILELIB.TSITIN t6, AFILELIB.TSITXN t7
WHERE t4.INORNO = t7.XTORNO AND t7.XTORNO = t6.ITORNO AND t6.ITORNO = T5.XNORNO AND t4.ININVR = t7.XTINVR 
AND t7.XTINVR = t6.ITINVR AND t7.XTITNO = t6.ITITNO AND t6.ITCSNO = t1.CUSNO AND t6.ITITNO = t3.BZAITX 
AND t3.BZAITX = t2.ITNBR AND t4.INWHSE = t6.ITWHSE AND t6.ITINVR = T5.XNINVR AND t6.ITCSNO = t7.XCUS# 
AND t7.XCUS# = t4.INCSNO AND t7.XTITSQ = t6.ITITSQ AND t4.INRIDT = t7.XRIDAT AND t7.XRIDAT = t6.ITRIDT
AND ((t4.INWHSE='335') 
AND (t4.INIVDT>= 20210101 
And t4.INIVDT<= int(substr(trim(char(CURRENT DATE)),1,4)||substr(trim(char(CURRENT DATE)),6,2)||substr(trim(char(CURRENT DATE)),9,2))) AND (t6.ITSHQT>0))
ORDER BY t4.INIVDT,T5.XNTRPN





