
SELECT t1.AASCN#, t1.AAAUSR,t1.AAAPGM,t1.AACOD1,t1.AACOD2,t1.AAFWHS,t1.AATRP#,t1.AADRP#,t1.AAORD#,t1.AAISQ#,t1.AAITM#,STR(t1.AASER#) AS SN,t1.AAUCC#,t1.AATQTY,t1.AACUS#,t1.AABOL#,t1.AAEBDG,	t1.AAEQP#,t1.AAADAT,t1.AAATIM
FROM  DISTLIB.ACTAUDT t1
