-- Ashton Discontinued query, created on Nov.26 and referred on RK_ONHAND

SELECT  a.ITNBR, a.HOUSE, a.ITCLS, a.MOHTQ, a.WHSLC, a.QTSYR, a.ITDSC, a.MFPUS,a.DOFLS,a.QTSMO,a.BEGIN,
a.RECMO,a.OPEN_PO,a.LDQOH,b.PAMNT "UnitPrice($USD)",b.PAMNT*a.MOHTQ "AMT($USD)",
(CASE 
    WHEN a.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(a.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(a.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)) AS "DATE",
DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2))) as "INTERVAL",
(CASE
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<30 THEN 'a. 0~1 Month'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<60 THEN 'b. 1~2 Months'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<90 THEN 'c. 2~3 Months'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<120 THEN 'd. 3~4 Months'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<150 THEN 'e. 4~5 Months'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<180 THEN 'f. 5~6 Months'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<360 THEN 'g. 6~12 Months'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<540 THEN 'h. 1~1.5 Years'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<720 THEN 'i. 1.5~2 Years'
	WHEN DAYS(CURRENT DATE) - DAYS(DATE('20'||SUBSTR(a.DOFLS,2,2)||'-'||SUBSTR(a.DOFLS,4,2)||'-'||SUBSTR(a.DOFLS,6,2)))<1080 THEN 'j. 2~3 Years'	
	ELSE 'k. Over 3 Years' END) RANGE
FROM
(
SELECT T1.ITNBR, T1.HOUSE, T1.ITCLS, T1.MOHTQ, T1.WHSLC, T1.QTSYR, T2.ITDSC, T4.MFPUS,T1.DOFLS,T1.QTSMO,T1.BEGIN,T1.RECMO,T1.MPUPQ OPEN_PO,T1.LDQOH
FROM AMFLIBA.ITEMBL T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3, AFILELIB.ITMEXT T4
WHERE T2.ITCLS = T1.ITCLS AND T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND T1.HOUSE='335' and T1.ITNBR = t4.itnbr AND T1.MOHTQ<>0
) AS a

LEFT JOIN  

(SELECT *
FROM AFILELIB.PRICE a
WHERE a.PRICCD in ('FOBARC')) b on a.itnbr=b.pitem




--  to get current on hand
SELECT ITNBR,HOUSE,ITCLS,Product,MFPUS,SUM(MOHTQ) OnHand, SUM("AMT($USD)") "AMT($USD)"
FROM (
SELECT a.ITNBR,a.HOUSE, a.ITCLS, a.MOHTQ, b.PAMNT "UP($USD)",
(CASE 
    WHEN a.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(a.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(a.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
(CASE 
    WHEN b.PAMNT IS NULL AND a.ITCLS NOT LIKE 'Z%' THEN 0
	WHEN b.PAMNT IS NULL AND a.ITCLS LIKE 'Z%' THEN a.MOHTQ*150
	ELSE a.MOHTQ*b.PAMNT END) as "AMT($USD)", 
'CurrentInv' as "Type"
FROM 
(SELECT T1.ITNBR,T1.HOUSE, T1.ITCLS, T1.MOHTQ, T1.WHSLC, T2.ITDSC    
FROM AMFLIBA.ITEMBL T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3 
WHERE  T2.ITCLS = T1.ITCLS AND T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND ((T1.HOUSE='335') AND (T1.MOHTQ<>0))
ORDER BY T1.ITNBR) as a
LEFT JOIN (SELECT PRICE.PITEM, PRICE.PAMNT FROM AFILELIB.PRICE PRICE WHERE PRICE.PRICCD='FOBARC' ORDER BY PRICE.PITEM) as b 
ON a.ITNBR = b.PITEM) 
GROUP BY ITNBR,HOUSE,ITCLS,Product,MFPUS