-- AS TRX BY PRODUCT AND INBOUND

SELECT s1.type, s1.Year, s1.Month, 
sum(CASE WHEN s1.Product in ('UPH') THEN s1.QTY ELSE 0 END) AS UPH,
sum(CASE WHEN s1.Product in ('CG') THEN s1.QTY ELSE 0 END) AS CG,
sum(CASE WHEN s1.Product in ('RP') THEN s1.QTY ELSE 0 END) AS RP,
sum(CASE WHEN s1.Product in ('CHECKING') THEN s1.QTY ELSE 0 END) AS CHECKING,
sum(s1.Qty) as Total

FROM 
(
SELECT t1.TCODE, t1.ORDNO, t1.ITNBR, t2.ITCLS, t1.HOUSE, t1.UPDDT, t1.UPDTM, t1.TRQTY, 
(CASE WHEN t1.TCODE IN ('SS') THEN ABS(t1.TRQTY) ELSE t1.TRQTY END) AS QTY,
(CASE 
    WHEN t2.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
(CASE
	WHEN t1.TCODE in ('IA') AND t1.TRQTY<0 THEN 'OUT'
	WHEN t1.TCODE in ('IA') AND t1.TRQTY>0 THEN 'IN'
	WHEN t1.TCODE in ('SA','IS','SS') THEN 'OUT'
	WHEN t1.TCODE in ('RP','RC') THEN 'IN'
ELSE 'CHECKING' END) AS type,

DATE('20'||SUBSTR(t1.UPDDT,2,2)||'-'||SUBSTR(t1.UPDDT,4,2)||'-'||SUBSTR(t1.UPDDT,6,2)) as Date,
Week(DATE('20'||SUBSTR(t1.UPDDT,2,2)||'-'||SUBSTR(t1.UPDDT,4,2)||'-'||SUBSTR(t1.UPDDT,6,2))) as Week,
Month(DATE('20'||SUBSTR(t1.UPDDT,2,2)||'-'||SUBSTR(t1.UPDDT,4,2)||'-'||SUBSTR(t1.UPDDT,6,2))) as Month,
Year(DATE('20'||SUBSTR(t1.UPDDT,2,2)||'-'||SUBSTR(t1.UPDDT,4,2)||'-'||SUBSTR(t1.UPDDT,6,2))) as Year 


FROM AMFLIBA.IMHIST t1, AMFLIBA.ITMRVA t2, AMFLIBA.WHSMST t3  
WHERE t2.ITNBR = t1.ITNBR AND t2.STID = t3.STID AND t1.HOUSE = t3.WHID AND t1.HOUSE IN ('335') 
AND (t1.UPDDT>=? And t1.UPDDT<=?) AND (t1.TRQTY<>0) and t1.TCODE IN ('SA')

UNION ALL
-- archived data for transaction in whse335
SELECT t1.IMHTRANSACTIONCODE, t1.IMHORDERNUMBER, t1.IMHITEMNUMBER, t2.ITCLS, t1.IMHWAREHOUSE, t1.IMHUPDATEPERIODDATE, t1.IMHUPDATETIME, t1.IMHTRANSACTIONQUANTITY, 
(CASE WHEN t1.IMHTRANSACTIONCODE IN ('SS') THEN ABS(t1.IMHTRANSACTIONQUANTITY) ELSE t1.IMHTRANSACTIONQUANTITY END) AS QTY,
(CASE 
    WHEN t2.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(t1.IMHITEMNUMBER,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(t1.IMHITEMNUMBER,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
(CASE
	WHEN t1.IMHTRANSACTIONCODE in ('IA') AND t1.IMHTRANSACTIONQUANTITY<0 THEN 'OUT'
	WHEN t1.IMHTRANSACTIONCODE in ('IA') AND t1.IMHTRANSACTIONQUANTITY>0 THEN 'IN'
	WHEN t1.IMHTRANSACTIONCODE in ('SS') AND t1.IMHTRANSACTIONQUANTITY<0 THEN 'IN'
	WHEN t1.IMHTRANSACTIONCODE in ('SS') AND t1.IMHTRANSACTIONQUANTITY>0 THEN 'OUT'
	WHEN t1.IMHTRANSACTIONCODE in ('SS') AND t1.IMHTRANSACTIONQUANTITY>0 THEN 'OUT'
	WHEN t1.IMHTRANSACTIONCODE in ('SA','IS') THEN 'OUT'
	WHEN t1.IMHTRANSACTIONCODE in ('RP','RC') THEN 'IN'
ELSE 'CHECKING' END) AS type,

DATE('20'||SUBSTR(t1.IMHUPDATEPERIODDATE,2,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,4,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,6,2)) as Date,
Week(DATE('20'||SUBSTR(t1.IMHUPDATEPERIODDATE,2,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,4,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,6,2))) as Week,
Month(DATE('20'||SUBSTR(t1.IMHUPDATEPERIODDATE,2,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,4,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,6,2))) as Month,
Year(DATE('20'||SUBSTR(t1.IMHUPDATEPERIODDATE,2,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,4,2)||'-'||SUBSTR(t1.IMHUPDATEPERIODDATE,6,2))) as Year 

FROM ASHLEYARCH.TBL_IMHIST_ARCHIVE t1, AMFLIBA.ITMRVA t2, AMFLIBA.WHSMST t3  
WHERE t2.ITNBR = t1.IMHITEMNUMBER AND t2.STID = t3.STID AND t1.IMHWAREHOUSE = t3.WHID AND t1.IMHWAREHOUSE IN ('335') 
AND (t1.IMHUPDATEPERIODDATE>=? And t1.IMHUPDATEPERIODDATE<=?) AND (t1.IMHTRANSACTIONQUANTITY<>0) and t1.IMHTRANSACTIONCODE IN ('SA')


) AS s1
where s1.type in ('OUT')
GROUP BY s1.type, s1.Year, s1.Month
ORDER BY s1.Year, s1.Month

