-- OnHand + TRANSACTONS, created by Jimshen on Nov.20.2021

SELECT ITNBR,HOUSE,ITCLS,Product,
SUM(CASE WHEN "Type" IN ('CurrentInv') THEN MOHTQ ELSE 0 END) AS "CurrentStockQty",
SUM(CASE WHEN "Type" IN ('IN') THEN MOHTQ ELSE 0 END) AS "IN_QTY",
SUM(CASE WHEN "Type" IN ('OUT') THEN MOHTQ ELSE 0 END) AS "OUT_QTY",
SUM(CASE WHEN "Type" IN ('CurrentInv') THEN "AMT($USD)" ELSE 0 END) AS "CurrentStockAMT",
SUM(CASE WHEN "Type" IN ('IN') THEN "AMT($USD)" ELSE 0 END) AS "IN_AMT",
SUM(CASE WHEN "Type" IN ('OUT') THEN "AMT($USD)" ELSE 0 END) AS "OUT_AMT",

SUM(CASE WHEN "Type" IN ('CurrentInv') THEN MOHTQ ELSE 0 END) + 
SUM(CASE WHEN "Type" IN ('OUT') THEN MOHTQ ELSE 0 END) - SUM(CASE WHEN "Type" IN ('IN') THEN MOHTQ ELSE 0 END) as "BeginningQty",

SUM(CASE WHEN "Type" IN ('CurrentInv') THEN "AMT($USD)" ELSE 0 END) +SUM(CASE WHEN "Type" IN ('OUT') THEN "AMT($USD)" ELSE 0 END)
-SUM(CASE WHEN "Type" IN ('IN') THEN "AMT($USD)" ELSE 0 END) as "BeginningAMT"

FROM
(
-- Above UNION ALL syntax is to get current on hand  
SELECT a.ITNBR,a.HOUSE, a.ITCLS, a.MOHTQ, b.PAMNT "UP($USD)",
(CASE 
    WHEN a.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(a.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(a.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
(CASE 
    WHEN b.PAMNT IS NULL AND a.ITCLS NOT LIKE 'Z%' THEN 0
	WHEN b.PAMNT IS NULL AND a.ITCLS LIKE 'Z%' THEN a.MOHTQ*150
	ELSE a.MOHTQ*b.PAMNT END) as "AMT($USD)", 
'CurrentInv' as "Type"
FROM 
(SELECT T1.ITNBR,T1.HOUSE, T1.ITCLS, T1.MOHTQ, T1.WHSLC, T2.ITDSC    
FROM AMFLIBA.ITEMBL T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3 
WHERE  T2.ITCLS = T1.ITCLS AND T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND ((T1.HOUSE='335') AND (T1.MOHTQ<>0))
ORDER BY T1.ITNBR) as a
LEFT JOIN (SELECT PRICE.PITEM, PRICE.PAMNT FROM AFILELIB.PRICE PRICE WHERE PRICE.PRICCD='FOBARC' ORDER BY PRICE.PITEM) as b 
ON a.ITNBR = b.PITEM 

UNION ALL
-- under UNION ALL syntax is to get transactoins in and out  
SELECT X.ITNBR, X.HOUSE, X.ITCLS, X.TRQTY, Y.PAMNT "UP($USD)",
(CASE 
    WHEN X.ITCLS NOT LIKE 'Z%' THEN 'RP'
	WHEN SUBSTR(X.ITNBR,1,4)='100-' THEN 'CG'
	WHEN SUBSTR(X.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
	ELSE 'UPH' END) as Product,
(CASE 
    WHEN Y.PAMNT IS NULL AND X.ITCLS NOT LIKE 'Z%' THEN 0
	WHEN Y.PAMNT IS NULL AND X.ITCLS LIKE 'Z%' THEN X.TRQTY*150
	ELSE X.TRQTY*Y.PAMNT END) as "AMT($USD)",
(CASE 
		WHEN X.TCODE IN ('RP') THEN 'IN'
		WHEN X.TCODE IN ('SA') THEN 'OUT'
		ELSE 'CHECK' END ) as "Type"

FROM
(
SELECT T1.TCODE, T1.ITNBR, T1.HOUSE, T2.ITCLS, T1.TRQTY
FROM AMFLIBA.IMHIST T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3
WHERE T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND T1.HOUSE='335' 
AND T1.UPDDT BETWEEN '1211101' AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
AND T1.TRQTY<>0 AND T1.TCODE in ('RP','SA') 
ORDER BY T1.ITNBR 
) X
LEFT JOIN (SELECT PRICE.PITEM, PRICE.PAMNT FROM AFILELIB.PRICE PRICE WHERE PRICE.PRICCD='FOBARC' ORDER BY PRICE.PITEM) as Y 
ON X.ITNBR = Y.PITEM
)
GROUP BY ITNBR,HOUSE,ITCLS,Product